// The league registry data table. Split out from registry.ts so the logic module
// (types + derived lookups/helpers) stays reviewable; this file is pure data.
import type { LeagueRegistryEntry } from "./registry";

export const LEAGUES = [
  {
    id: "nba",
    sport: "basketball",
    label: "NBA",
    short: "NBA",
    region: "USA",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba", parser: "team" },
  },
  {
    id: "wnba",
    sport: "basketball",
    label: "WNBA",
    short: "WNBA",
    region: "USA",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "wnba", parser: "team" },
  },
  {
    id: "ncaab",
    sport: "basketball",
    label: "NCAA Men's",
    short: "NCAAB",
    region: "USA",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "mens-college-basketball", parser: "team" },
  },
  {
    id: "mlb",
    sport: "baseball",
    label: "MLB",
    short: "MLB",
    region: "USA",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "mlb", parser: "team" },
  },
  {
    id: "nfl",
    sport: "american-football",
    label: "NFL",
    short: "NFL",
    region: "USA",
    streamCategory: "american-football",
    espn: { sport: "football", path: "nfl", parser: "team" },
  },
  {
    id: "ncaaf",
    sport: "american-football",
    label: "NCAA Football",
    short: "NCAAF",
    region: "USA",
    streamCategory: "american-football",
    espn: { sport: "football", path: "college-football", parser: "team" },
  },
  {
    id: "nhl",
    sport: "hockey",
    label: "NHL",
    short: "NHL",
    region: "USA/CAN",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "nhl", parser: "team" },
  },
  {
    id: "mls",
    sport: "soccer",
    label: "MLS",
    short: "MLS",
    region: "USA/CAN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.1", parser: "team" },
  },
  {
    id: "nwsl",
    sport: "soccer",
    label: "NWSL",
    short: "NWSL",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.nwsl", parser: "team" },
  },
  {
    id: "epl",
    sport: "soccer",
    label: "Premier League",
    short: "EPL",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.1", parser: "team" },
  },
  {
    id: "laliga",
    sport: "soccer",
    label: "LaLiga",
    short: "LALIGA",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.1", parser: "team" },
  },
  {
    id: "serie-a",
    sport: "soccer",
    label: "Serie A",
    short: "SERIE A",
    region: "ITA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ita.1", parser: "team" },
  },
  {
    id: "bundesliga",
    sport: "soccer",
    label: "Bundesliga",
    short: "BUN",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.1", parser: "team" },
  },
  {
    id: "ligue-1",
    sport: "soccer",
    label: "Ligue 1",
    short: "LIGUE 1",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.1", parser: "team" },
  },
  {
    id: "liga-mx",
    sport: "soccer",
    label: "Liga MX",
    short: "LIGA MX",
    region: "MEX",
    streamCategory: "football",
    espn: { sport: "soccer", path: "mex.1", parser: "team" },
  },
  {
    id: "ucl",
    sport: "soccer",
    label: "UEFA Champions League",
    short: "UCL",
    region: "EUR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.champions", parser: "team" },
  },
  {
    id: "uel",
    sport: "soccer",
    label: "UEFA Europa League",
    short: "UEL",
    region: "EUR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.europa", parser: "team" },
  },
  {
    id: "atp",
    sport: "tennis",
    label: "ATP Tour",
    short: "ATP",
    region: "INT",
    streamCategory: "tennis",
    espn: { sport: "tennis", path: "atp", parser: "tennis" },
  },
  {
    id: "wta",
    sport: "tennis",
    label: "WTA Tour",
    short: "WTA",
    region: "INT",
    streamCategory: "tennis",
    espn: { sport: "tennis", path: "wta", parser: "tennis" },
  },
  {
    id: "ufc",
    sport: "combat",
    label: "UFC",
    short: "UFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "ufc", parser: "event" },
  },
  {
    id: "afl",
    sport: "aussie-rules",
    label: "AFL",
    short: "AFL",
    region: "AUS",
    streamCategory: "afl",
    espn: { sport: "australian-football", path: "afl", parser: "team" },
  },
  {
    id: "fifa-world",
    sport: "soccer",
    label: "FIFA World Cup",
    short: "WC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.world", parser: "team" },
  },
  {
    id: "world-football",
    sport: "soccer",
    label: "International Football",
    short: "INTL",
    region: "INT",
    streamCategory: "football",
  },
  {
    id: "gridiron",
    sport: "american-football",
    label: "CFL / ELF",
    short: "CFL/ELF",
    region: "INT",
    streamCategory: "american-football",
  },
  {
    id: "rugby",
    sport: "rugby",
    label: "Rugby",
    short: "RUGBY",
    region: "INT",
    streamCategory: "rugby",
  },
  {
    id: "volleyball",
    sport: "volleyball",
    label: "Volleyball",
    short: "VB",
    region: "INT",
    streamCategory: "volleyball",
  },
  {
    id: "cricket",
    sport: "cricket",
    label: "Cricket",
    short: "CRICKET",
    region: "INT",
    streamCategory: "cricket",
  },
  {
    id: "wrestling",
    sport: "combat",
    label: "Pro Wrestling",
    short: "WREST",
    region: "INT",
    streamCategory: "fight",
  },
  {
    id: "f1",
    sport: "racing",
    label: "Formula 1",
    short: "F1",
    region: "INT",
    streamCategory: "motor-sports",
    espn: { sport: "racing", path: "f1", parser: "event" },
  },
  {
    id: "pga",
    sport: "golf",
    label: "PGA Tour",
    short: "PGA",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "pga", parser: "event" },
  },
  // --- Auto-generated from ESPN catalog (games-only, validated scoreboards) ---
  {
    id: "usf-cfl",
    sport: "american-football",
    label: "Canadian Football League",
    short: "CFL",
    region: "INT",
    streamCategory: "american-football",
    espn: { sport: "football", path: "cfl", parser: "team" },
  },
  {
    id: "usf-ufl",
    sport: "american-football",
    label: "United Football League",
    short: "UFL",
    region: "INT",
    streamCategory: "american-football",
    espn: { sport: "football", path: "ufl", parser: "team" },
  },
  {
    id: "usf-xfl",
    sport: "american-football",
    label: "XFL",
    short: "XFL",
    region: "INT",
    streamCategory: "american-football",
    espn: { sport: "football", path: "xfl", parser: "team" },
  },
  {
    id: "bsb-llb",
    sport: "baseball",
    label: "Little League Baseball",
    short: "LITTLE LEA",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "llb", parser: "team" },
  },
  {
    id: "bsb-lls",
    sport: "baseball",
    label: "Little League Softball",
    short: "LITTLE LEA",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "lls", parser: "team" },
  },
  {
    id: "bsb-caribbean-series",
    sport: "baseball",
    label: "Caribbean Series",
    short: "CBWS",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "caribbean-series", parser: "team" },
  },
  {
    id: "bsb-college-baseball",
    sport: "baseball",
    label: "NCAA Baseball",
    short: "CBASE",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "college-baseball", parser: "team" },
  },
  {
    id: "bsb-college-softball",
    sport: "baseball",
    label: "NCAA Softball",
    short: "CSOFT",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "college-softball", parser: "team" },
  },
  {
    id: "bsb-dominican-winter-league",
    sport: "baseball",
    label: "Dominican Winter League",
    short: "DOMWL",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "dominican-winter-league", parser: "team" },
  },
  {
    id: "bsb-mexican-winter-league",
    sport: "baseball",
    label: "Mexican League",
    short: "LMB",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "mexican-winter-league", parser: "team" },
  },
  {
    id: "bsb-olympics-baseball",
    sport: "baseball",
    label: "Olympics Men's Baseball",
    short: "OLYBB",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "olympics-baseball", parser: "team" },
  },
  {
    id: "bsb-puerto-rican-winter-league",
    sport: "baseball",
    label: "Puerto Rican Winter League",
    short: "PUERT",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "puerto-rican-winter-league", parser: "team" },
  },
  {
    id: "bsb-venezuelan-winter-league",
    sport: "baseball",
    label: "Venezuelan Winter League",
    short: "VENWL",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "venezuelan-winter-league", parser: "team" },
  },
  {
    id: "bsb-world-baseball-classic",
    sport: "baseball",
    label: "World Baseball Classic",
    short: "WBBC",
    region: "INT",
    streamCategory: "baseball",
    espn: { sport: "baseball", path: "world-baseball-classic", parser: "team" },
  },
  {
    id: "hoop-nba-summer-orlando",
    sport: "basketball",
    label: "Orlando Summer League",
    short: "NBAOR",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-orlando", parser: "team" },
  },
  {
    id: "hoop-nba-summer-las-vegas",
    sport: "basketball",
    label: "Las Vegas Summer League",
    short: "NBALV",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-las-vegas", parser: "team" },
  },
  {
    id: "hoop-fiba",
    sport: "basketball",
    label: "FIBA World Cup",
    short: "FIBA",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "fiba", parser: "team" },
  },
  {
    id: "hoop-mens-olympics-basketball",
    sport: "basketball",
    label: "Olympics Men's Basketball",
    short: "OLYMPICS",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "mens-olympics-basketball", parser: "team" },
  },
  {
    id: "hoop-nba-summer-california",
    sport: "basketball",
    label: "NBA California Classic Summer League",
    short: "NBACC",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-california", parser: "team" },
  },
  {
    id: "hoop-nba-summer-golden-state",
    sport: "basketball",
    label: "Golden State Summer League",
    short: "NBAGS",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-golden-state", parser: "team" },
  },
  {
    id: "hoop-nba-summer-sacramento",
    sport: "basketball",
    label: "Sacramento Summer League",
    short: "NBAGS",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-sacramento", parser: "team" },
  },
  {
    id: "hoop-nba-summer-utah",
    sport: "basketball",
    label: "Salt Lake City Summer League",
    short: "NBAUT",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-summer-utah", parser: "team" },
  },
  {
    id: "hoop-nbl",
    sport: "basketball",
    label: "National Basketball League",
    short: "NBL",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nbl", parser: "team" },
  },
  {
    id: "hoop-womens-olympics-basketball",
    sport: "basketball",
    label: "Olympics Women's Basketball",
    short: "OLYMPICS",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "womens-olympics-basketball", parser: "team" },
  },
  {
    id: "hoop-nba-development",
    sport: "basketball",
    label: "NBA G League",
    short: "NBA G LEAG",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "nba-development", parser: "team" },
  },
  {
    id: "hoop-womens-college-basketball",
    sport: "basketball",
    label: "NCAA Women's Basketball",
    short: "NCAAW",
    region: "INT",
    streamCategory: "basketball",
    espn: { sport: "basketball", path: "womens-college-basketball", parser: "team" },
  },
  {
    id: "mma-pancrase",
    sport: "combat",
    label: "Pancrase",
    short: "PANCRASE",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "pancrase", parser: "event" },
  },
  {
    id: "mma-proelite",
    sport: "combat",
    label: "ProElite",
    short: "PE",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "proelite", parser: "event" },
  },
  {
    id: "mma-absolute",
    sport: "combat",
    label: "Absolute Championship Berkut",
    short: "ACB",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "absolute", parser: "event" },
  },
  {
    id: "mma-affliction",
    sport: "combat",
    label: "Affliction",
    short: "AFFLICTION",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "affliction", parser: "event" },
  },
  {
    id: "mma-bang-fighting",
    sport: "combat",
    label: "Bang Fighting Championships",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "bang-fighting", parser: "event" },
  },
  {
    id: "mma-banni-fight",
    sport: "combat",
    label: "Banni Fight Combat",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "banni-fight", parser: "event" },
  },
  {
    id: "mma-banzay",
    sport: "combat",
    label: "Banzay Fight Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "banzay", parser: "event" },
  },
  {
    id: "mma-barracao",
    sport: "combat",
    label: "Barracao Fight Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "barracao", parser: "event" },
  },
  {
    id: "mma-battlezone",
    sport: "combat",
    label: "Battlezone Fighting Championships",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "battlezone", parser: "event" },
  },
  {
    id: "mma-bellator",
    sport: "combat",
    label: "Bellator Fighting Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "bellator", parser: "event" },
  },
  {
    id: "mma-benevides",
    sport: "combat",
    label: "Benevides Fight Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "benevides", parser: "event" },
  },
  {
    id: "mma-big-fight",
    sport: "combat",
    label: "Big Fight Champions",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "big-fight", parser: "event" },
  },
  {
    id: "mma-blackout",
    sport: "combat",
    label: "Blackout Fighting Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "blackout", parser: "event" },
  },
  {
    id: "mma-bosnia",
    sport: "combat",
    label: "Bosnia Fight Championship",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "bosnia", parser: "event" },
  },
  {
    id: "mma-boxe",
    sport: "combat",
    label: "Boxe Fight Combat",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "boxe", parser: "event" },
  },
  {
    id: "mma-brazilian-freestyle",
    sport: "combat",
    label: "Brazilian Freestyle Circuit",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "brazilian-freestyle", parser: "event" },
  },
  {
    id: "mma-budo",
    sport: "combat",
    label: "Budo Fighting Championships",
    short: "BFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "budo", parser: "event" },
  },
  {
    id: "mma-cage-warriors",
    sport: "combat",
    label: "Cage Warriors Fighting Championship",
    short: "CWFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "cage-warriors", parser: "event" },
  },
  {
    id: "mma-dream",
    sport: "combat",
    label: "Dream",
    short: "DREAM",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "dream", parser: "event" },
  },
  {
    id: "mma-fng",
    sport: "combat",
    label: "Fight Nights Global",
    short: "FNG",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "fng", parser: "event" },
  },
  {
    id: "mma-ifc",
    sport: "combat",
    label: "Invicta FC",
    short: "IFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "ifc", parser: "event" },
  },
  {
    id: "mma-ifl",
    sport: "combat",
    label: "International Fight League",
    short: "IFL",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "ifl", parser: "event" },
  },
  {
    id: "mma-k1",
    sport: "combat",
    label: "K-1",
    short: "K-1",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "k1", parser: "event" },
  },
  {
    id: "mma-ksw",
    sport: "combat",
    label: "Konfrontacja Sztuk Walki",
    short: "KSW",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "ksw", parser: "event" },
  },
  {
    id: "mma-lfa",
    sport: "combat",
    label: "Legacy Fighting Alliance",
    short: "LFA",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "lfa", parser: "event" },
  },
  {
    id: "mma-lfc",
    sport: "combat",
    label: "Legacy Fighting Championship",
    short: "LFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "lfc", parser: "event" },
  },
  {
    id: "mma-m1",
    sport: "combat",
    label: "M-1 Mix-Fight Championship",
    short: "M-1",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "m1", parser: "event" },
  },
  {
    id: "mma-mfc",
    sport: "combat",
    label: "Maximum Fighting Championship",
    short: "MAX",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "mfc", parser: "event" },
  },
  {
    id: "mma-mvp",
    sport: "combat",
    label: "MVP",
    short: "MVP",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "mvp", parser: "event" },
  },
  {
    id: "mma-ofc",
    sport: "combat",
    label: "One Fighting Championship",
    short: "OFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "ofc", parser: "event" },
  },
  {
    id: "mma-other",
    sport: "combat",
    label: "Other",
    short: "OTHER",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "other", parser: "event" },
  },
  {
    id: "mma-pfl",
    sport: "combat",
    label: "Professional Fighters League",
    short: "PFL",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "pfl", parser: "event" },
  },
  {
    id: "mma-pride",
    sport: "combat",
    label: "PRIDE Fighting Championships",
    short: "PRIDE",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "pride", parser: "event" },
  },
  {
    id: "mma-rfa",
    sport: "combat",
    label: "Resurrection Fighting Alliance",
    short: "RFA",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "rfa", parser: "event" },
  },
  {
    id: "mma-rizin",
    sport: "combat",
    label: "Rizin Fight Federation",
    short: "RFF",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "rizin", parser: "event" },
  },
  {
    id: "mma-roc",
    sport: "combat",
    label: "Ring of Combat",
    short: "ROC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "roc", parser: "event" },
  },
  {
    id: "mma-sfl",
    sport: "combat",
    label: "Super Fight League",
    short: "SFL",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "sfl", parser: "event" },
  },
  {
    id: "mma-shark-fights",
    sport: "combat",
    label: "Shark Fights",
    short: "SHARK",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "shark-fights", parser: "event" },
  },
  {
    id: "mma-shooto-brazil",
    sport: "combat",
    label: "Shooto Brazil",
    short: "SHOOTOB",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "shooto-brazil", parser: "event" },
  },
  {
    id: "mma-shooto-japan",
    sport: "combat",
    label: "Shooto Japan",
    short: "SHOOTOJ",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "shooto-japan", parser: "event" },
  },
  {
    id: "mma-shoxc",
    sport: "combat",
    label: "ShoXC: Showtime Xtreme Combat",
    short: "SHOXC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "shoxc", parser: "event" },
  },
  {
    id: "mma-strikeforce",
    sport: "combat",
    label: "Strikeforce",
    short: "SF",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "strikeforce", parser: "event" },
  },
  {
    id: "mma-tfc",
    sport: "combat",
    label: "Titan Fighting Championships",
    short: "TFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "tfc", parser: "event" },
  },
  {
    id: "mma-tpf",
    sport: "combat",
    label: "Tachi Palace Fights",
    short: "TPF",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "tpf", parser: "event" },
  },
  {
    id: "mma-wec",
    sport: "combat",
    label: "World Extreme Cagefighting",
    short: "WEC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "wec", parser: "event" },
  },
  {
    id: "mma-xfc",
    sport: "combat",
    label: "Xtreme Fighting Championships",
    short: "XFC",
    region: "INT",
    streamCategory: "fight",
    espn: { sport: "mma", path: "xfc", parser: "event" },
  },
  {
    id: "golf-tgl",
    sport: "golf",
    label: "TGL",
    short: "TGL",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "tgl", parser: "event" },
  },
  {
    id: "golf-champions-tour",
    sport: "golf",
    label: "PGA TOUR Champions",
    short: "SGA",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "champions-tour", parser: "event" },
  },
  {
    id: "golf-eur",
    sport: "golf",
    label: "DP World Tour",
    short: "EUR",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "eur", parser: "event" },
  },
  {
    id: "golf-liv",
    sport: "golf",
    label: "LIV Golf Invitational Series",
    short: "LIV",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "liv", parser: "event" },
  },
  {
    id: "golf-lpga",
    sport: "golf",
    label: "Ladies Pro Golf Association",
    short: "LPGA",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "lpga", parser: "event" },
  },
  {
    id: "golf-mens-olympics-golf",
    sport: "golf",
    label: "Olympic Golf - Men",
    short: "OLYM",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "mens-olympics-golf", parser: "event" },
  },
  {
    id: "golf-ntw",
    sport: "golf",
    label: "Korn Ferry Tour",
    short: "KORN FERRY",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "ntw", parser: "event" },
  },
  {
    id: "golf-womens-olympics-golf",
    sport: "golf",
    label: "Olympic Golf - Women",
    short: "OLYW",
    region: "INT",
    streamCategory: "golf",
    espn: { sport: "golf", path: "womens-olympics-golf", parser: "event" },
  },
  {
    id: "puck-olympics-womens-ice-hockey",
    sport: "hockey",
    label: "Women's Ice Hockey",
    short: "WOMEN'S IC",
    region: "INT",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "olympics-womens-ice-hockey", parser: "team" },
  },
  {
    id: "puck-hockey-world-cup",
    sport: "hockey",
    label: "World Cup of Hockey",
    short: "WCH",
    region: "INT",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "hockey-world-cup", parser: "team" },
  },
  {
    id: "puck-mens-college-hockey",
    sport: "hockey",
    label: "NCAA Men's Ice Hockey",
    short: "NCAAH",
    region: "INT",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "mens-college-hockey", parser: "team" },
  },
  {
    id: "puck-olympics-mens-ice-hockey",
    sport: "hockey",
    label: "Men's Ice Hockey",
    short: "MEN'S ICE ",
    region: "INT",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "olympics-mens-ice-hockey", parser: "team" },
  },
  {
    id: "puck-womens-college-hockey",
    sport: "hockey",
    label: "NCAA Women's Hockey",
    short: "CWHOC",
    region: "INT",
    streamCategory: "hockey",
    espn: { sport: "hockey", path: "womens-college-hockey", parser: "team" },
  },
  {
    id: "race-irl",
    sport: "racing",
    label: "IndyCar Series",
    short: "IRL",
    region: "INT",
    streamCategory: "motor-sports",
    espn: { sport: "racing", path: "irl", parser: "event" },
  },
  {
    id: "uefa.europa.conf-qual",
    sport: "soccer",
    label: "UEFA Conference League Qualifying",
    short: "UEFA CONFE",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.europa.conf_qual", parser: "team" },
  },
  {
    id: "fifa.wworldq.uefa",
    sport: "soccer",
    label: "FIFA Women's World Cup Qualifying - UEFA",
    short: "WWCQ - UEF",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.wworldq.uefa", parser: "team" },
  },
  {
    id: "uefa.euro-u21-qual",
    sport: "soccer",
    label: "UEFA European Under-21 Championship Qualifying",
    short: "EURO U-21 ",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.euro_u21_qual", parser: "team" },
  },
  {
    id: "ksa.kings.cup",
    sport: "soccer",
    label: "Saudi King's Cup",
    short: "SAUDI KING",
    region: "KSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ksa.kings.cup", parser: "team" },
  },
  {
    id: "sco.cis",
    sport: "soccer",
    label: "Scottish League Cup",
    short: "SLC",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.cis", parser: "team" },
  },
  {
    id: "uefa.champions-qual",
    sport: "soccer",
    label: "UEFA Champions League Qualifying",
    short: "UEFA CHAMP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.champions_qual", parser: "team" },
  },
  {
    id: "jpn.1",
    sport: "soccer",
    label: "Japanese J.League",
    short: "JAPANESE J",
    region: "JPN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "jpn.1", parser: "team" },
  },
  {
    id: "nga.1",
    sport: "soccer",
    label: "Nigerian Professional League",
    short: "NIGERIAN P",
    region: "NGA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "nga.1", parser: "team" },
  },
  {
    id: "fra.2",
    sport: "soccer",
    label: "French Ligue 2",
    short: "LIGUE 2",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.2", parser: "team" },
  },
  {
    id: "ger.2",
    sport: "soccer",
    label: "German 2. Bundesliga",
    short: "2. BUNDESL",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.2", parser: "team" },
  },
  {
    id: "gha.1",
    sport: "soccer",
    label: "Ghanaian Premier League",
    short: "GHANAIAN P",
    region: "GHA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "gha.1", parser: "team" },
  },
  {
    id: "ken.1",
    sport: "soccer",
    label: "Kenyan Premier League",
    short: "KENYAN PRE",
    region: "KEN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ken.1", parser: "team" },
  },
  {
    id: "ned.3",
    sport: "soccer",
    label: "Dutch Tweede Divisie",
    short: "DUTCH TWEE",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.3", parser: "team" },
  },
  {
    id: "por.1",
    sport: "soccer",
    label: "Portuguese Primeira Liga",
    short: "PORTUGUESE",
    region: "POR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "por.1", parser: "team" },
  },
  {
    id: "usa.usl.1",
    sport: "soccer",
    label: "USL Championship",
    short: "USL CHAMPI",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.usl.1", parser: "team" },
  },
  {
    id: "arg.2",
    sport: "soccer",
    label: "Argentine Nacional B",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.2", parser: "team" },
  },
  {
    id: "ecu.1",
    sport: "soccer",
    label: "LigaPro Ecuador",
    short: "LIGAPRO EC",
    region: "ECU",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ecu.1", parser: "team" },
  },
  {
    id: "esp.w.1",
    sport: "soccer",
    label: "Spanish Liga F",
    short: "LIGA F",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.w.1", parser: "team" },
  },
  {
    id: "fifa.world.u17",
    sport: "soccer",
    label: "FIFA Under-17 World Cup",
    short: "FIFA U-17 ",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.world.u17", parser: "team" },
  },
  {
    id: "rsa.2",
    sport: "soccer",
    label: "South African First Division",
    short: "SOUTH AFRI",
    region: "RSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rsa.2", parser: "team" },
  },
  {
    id: "rus.1",
    sport: "soccer",
    label: "Russian Premier League",
    short: "RUSSIAN PR",
    region: "RUS",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rus.1", parser: "team" },
  },
  {
    id: "tha.1",
    sport: "soccer",
    label: "Thai League 1",
    short: "THAI PREMI",
    region: "THA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "tha.1", parser: "team" },
  },
  {
    id: "uefa.nations",
    sport: "soccer",
    label: "UEFA Nations League",
    short: "UEFA NATIO",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.nations", parser: "team" },
  },
  {
    id: "concacaf.gold-qual",
    sport: "soccer",
    label: "Concacaf Gold Cup Qualifying",
    short: "GOLD CUP Q",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.gold_qual", parser: "team" },
  },
  {
    id: "idn.1",
    sport: "soccer",
    label: "Indonesian Super League",
    short: "INDONESIAN",
    region: "IDN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "idn.1", parser: "team" },
  },
  {
    id: "ksa.1",
    sport: "soccer",
    label: "Saudi Pro League",
    short: "SAUDI PRO ",
    region: "KSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ksa.1", parser: "team" },
  },
  {
    id: "rsa.1",
    sport: "soccer",
    label: "South African Premiership",
    short: "SOUTH AFRI",
    region: "RSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rsa.1", parser: "team" },
  },
  {
    id: "uga.1",
    sport: "soccer",
    label: "Ugandan Premier League",
    short: "UGANDA PRE",
    region: "UGA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uga.1", parser: "team" },
  },
  {
    id: "bra.copa-do-brazil",
    sport: "soccer",
    label: "Copa do Brasil",
    short: "COPA DO BR",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.copa_do_brazil", parser: "team" },
  },
  {
    id: "concacaf.leagues.cup",
    sport: "soccer",
    label: "Leagues Cup",
    short: "LEAGUES CU",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.leagues.cup", parser: "team" },
  },
  {
    id: "eng.w.1",
    sport: "soccer",
    label: "English Women's Super League",
    short: "WOMEN'S SU",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.w.1", parser: "team" },
  },
  {
    id: "fifa.friendly.w",
    sport: "soccer",
    label: "Women's International Friendly",
    short: "WOMEN'S IN",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.friendly.w", parser: "team" },
  },
  {
    id: "fifa.worldq.concacaf",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - Concacaf",
    short: "WCQ - CONC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.concacaf", parser: "team" },
  },
  {
    id: "ned.w.1",
    sport: "soccer",
    label: "Dutch Vrouwen Eredivisie",
    short: "DUTCH VROU",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.w.1", parser: "team" },
  },
  {
    id: "uefa.europa-qual",
    sport: "soccer",
    label: "UEFA Europa League Qualifying",
    short: "UEFA EUROP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.europa_qual", parser: "team" },
  },
  {
    id: "uru.2",
    sport: "soccer",
    label: "Segunda Divisi\u00f3n de Uruguay",
    short: "SEG",
    region: "URU",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uru.2", parser: "team" },
  },
  {
    id: "bra.1",
    sport: "soccer",
    label: "Brazilian Serie A",
    short: "BRAZIL SER",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.1", parser: "team" },
  },
  {
    id: "bra.3",
    sport: "soccer",
    label: "Brazilian Serie C",
    short: "BRAZIL SER",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.3", parser: "team" },
  },
  {
    id: "fifa.worldq.conmebol",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - CONMEBOL",
    short: "WCQ - CONM",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.conmebol", parser: "team" },
  },
  {
    id: "irl.1",
    sport: "soccer",
    label: "Irish Premier Division",
    short: "IRISH PREM",
    region: "IRL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "irl.1", parser: "team" },
  },
  {
    id: "ned.2",
    sport: "soccer",
    label: "Dutch Keuken Kampioen Divisie",
    short: "KEUKEN KAM",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.2", parser: "team" },
  },
  {
    id: "sco.2",
    sport: "soccer",
    label: "Scottish Championship",
    short: "SPFL CHAMP",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.2", parser: "team" },
  },
  {
    id: "tur.1",
    sport: "soccer",
    label: "Turkish Super Lig",
    short: "TURKISH SU",
    region: "TUR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "tur.1", parser: "team" },
  },
  {
    id: "arg.4",
    sport: "soccer",
    label: "Argentine Primera C",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.4", parser: "team" },
  },
  {
    id: "caf.nations-qual",
    sport: "soccer",
    label: "Africa Cup of Nations Qualifying",
    short: "AFCON QUAL",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.nations_qual", parser: "team" },
  },
  {
    id: "caf.w.nations",
    sport: "soccer",
    label: "Women's Africa Cup of Nations",
    short: "WOMEN'S AF",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.w.nations", parser: "team" },
  },
  {
    id: "chi.2",
    sport: "soccer",
    label: "Segunda Divisi\u00f3n de Chile",
    short: "SEG",
    region: "CHI",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chi.2", parser: "team" },
  },
  {
    id: "conmebol.libertadores",
    sport: "soccer",
    label: "CONMEBOL Libertadores",
    short: "CONMEBOL L",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "conmebol.libertadores", parser: "team" },
  },
  {
    id: "fifa.cwc",
    sport: "soccer",
    label: "FIFA Club World Cup",
    short: "CLUB WORLD",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.cwc", parser: "team" },
  },
  {
    id: "fifa.worldq.uefa",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - UEFA",
    short: "WCQ - UEFA",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.uefa", parser: "team" },
  },
  {
    id: "ind.1",
    sport: "soccer",
    label: "Indian Super League",
    short: "INDIAN SUP",
    region: "IND",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ind.1", parser: "team" },
  },
  {
    id: "per.1",
    sport: "soccer",
    label: "Peruvian Liga 1",
    short: "PERU LIGA ",
    region: "PER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "per.1", parser: "team" },
  },
  {
    id: "usa.w.usl.1",
    sport: "soccer",
    label: "USL Super League",
    short: "USL SUPER ",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.w.usl.1", parser: "team" },
  },
  {
    id: "bra.2",
    sport: "soccer",
    label: "Brazilian Serie B",
    short: "BRAZIL SER",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.2", parser: "team" },
  },
  {
    id: "bra.camp.carioca",
    sport: "soccer",
    label: "Brazilian Campeonato Carioca",
    short: "BRAZIL CAR",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.camp.carioca", parser: "team" },
  },
  {
    id: "concacaf.central.american.cup",
    sport: "soccer",
    label: "Concacaf Central American Cup",
    short: "CENTRAL AM",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.central.american.cup", parser: "team" },
  },
  {
    id: "cyp.1",
    sport: "soccer",
    label: "Cypriot First Division",
    short: "CYPRIOT FI",
    region: "CYP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "cyp.1", parser: "team" },
  },
  {
    id: "gre.1",
    sport: "soccer",
    label: "Greek Super League",
    short: "GREEK SUPE",
    region: "GRE",
    streamCategory: "football",
    espn: { sport: "soccer", path: "gre.1", parser: "team" },
  },
  {
    id: "par.1",
    sport: "soccer",
    label: "Paraguayan Primera Divisi\u00f3n",
    short: "PARAGUAYAN",
    region: "PAR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "par.1", parser: "team" },
  },
  {
    id: "uefa.euroq",
    sport: "soccer",
    label: "UEFA European Championship Qualifying",
    short: "EURO QUALI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.euroq", parser: "team" },
  },
  {
    id: "aff.championship",
    sport: "soccer",
    label: "ASEAN Championship",
    short: "ASEAN CHAM",
    region: "AFF",
    streamCategory: "football",
    espn: { sport: "soccer", path: "aff.championship", parser: "team" },
  },
  {
    id: "bol.1",
    sport: "soccer",
    label: "Bolivian Liga Profesional",
    short: "BOLIVIAN L",
    region: "BOL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bol.1", parser: "team" },
  },
  {
    id: "caf.cosafa",
    sport: "soccer",
    label: "COSAFA Cup",
    short: "COSAFA CUP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.cosafa", parser: "team" },
  },
  {
    id: "can.w.nsl",
    sport: "soccer",
    label: "Northern Super League",
    short: "NORTHERN S",
    region: "CAN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "can.w.nsl", parser: "team" },
  },
  {
    id: "chi.copa-chi",
    sport: "soccer",
    label: "Copa Chile",
    short: "COPA CHILE",
    region: "CHI",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chi.copa_chi", parser: "team" },
  },
  {
    id: "chn.1.promotion.relegation",
    sport: "soccer",
    label: "Chinese Super League Promotion/Relegation Playoffs",
    short: "CHINESE PR",
    region: "CHN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chn.1.promotion.relegation", parser: "team" },
  },
  {
    id: "club.friendly",
    sport: "soccer",
    label: "Club Friendly",
    short: "CLUB FRIEN",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "club.friendly", parser: "team" },
  },
  {
    id: "concacaf.gold",
    sport: "soccer",
    label: "Concacaf Gold Cup",
    short: "GOLD CUP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.gold", parser: "team" },
  },
  {
    id: "concacaf.nations.league",
    sport: "soccer",
    label: "Concacaf Nations League",
    short: "CONCACAF N",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.nations.league", parser: "team" },
  },
  {
    id: "concacaf.w.champions-cup",
    sport: "soccer",
    label: "Concacaf W Champions Cup",
    short: "W CHAMPION",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.w.champions_cup", parser: "team" },
  },
  {
    id: "concacaf.womens.championship",
    sport: "soccer",
    label: "Concacaf W Championship",
    short: "CONCACAF W",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.womens.championship", parser: "team" },
  },
  {
    id: "conmebol.sudamericana",
    sport: "soccer",
    label: "CONMEBOL Sudamericana",
    short: "CONMEBOL S",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "conmebol.sudamericana", parser: "team" },
  },
  {
    id: "fifa.conmebol.olympicsq",
    sport: "soccer",
    label: "CONMEBOL Pre-Olympic Tournament",
    short: "CONMEBOL P",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.conmebol.olympicsq", parser: "team" },
  },
  {
    id: "fifa.friendly-u21",
    sport: "soccer",
    label: "Under-21 International Friendly",
    short: "MEN'S U-21",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.friendly_u21", parser: "team" },
  },
  {
    id: "fifa.shebelieves",
    sport: "soccer",
    label: "SheBelieves Cup",
    short: "SHEBELIEVE",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.shebelieves", parser: "team" },
  },
  {
    id: "fifa.w.champions-cup",
    sport: "soccer",
    label: "FIFA Women's Champions Cup",
    short: "WOMEN'S CH",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.w.champions_cup", parser: "team" },
  },
  {
    id: "fifa.wcq.ply",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - Playoff Tournament",
    short: "WCQ - PLAY",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.wcq.ply", parser: "team" },
  },
  {
    id: "fifa.wwcq.ply",
    sport: "soccer",
    label: "FIFA Women's World Cup Qualifying - Playoff Tournament",
    short: "WWCQ - PLA",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.wwcq.ply", parser: "team" },
  },
  {
    id: "fifa.wworld.u17",
    sport: "soccer",
    label: "FIFA Under-17 Women's World Cup",
    short: "FIFA U-17 ",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.wworld.u17", parser: "team" },
  },
  {
    id: "global.arnold.clark-cup",
    sport: "soccer",
    label: "Arnold Clark Cup",
    short: "ARNOLD CLA",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.arnold.clark_cup", parser: "team" },
  },
  {
    id: "global.pinatar-cup",
    sport: "soccer",
    label: "Pinatar Cup",
    short: "PINATAR CU",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.pinatar_cup", parser: "team" },
  },
  {
    id: "global.toulon",
    sport: "soccer",
    label: "Maurice Revello Tournament",
    short: "MAURICE RE",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.toulon", parser: "team" },
  },
  {
    id: "global.wchamps-cup",
    sport: "soccer",
    label: "Women's International Champions Cup",
    short: "WOMEN'S IC",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.wchamps_cup", parser: "team" },
  },
  {
    id: "mys.1",
    sport: "soccer",
    label: "Malaysian Super League",
    short: "MALAYSIAN ",
    region: "MYS",
    streamCategory: "football",
    espn: { sport: "soccer", path: "mys.1", parser: "team" },
  },
  {
    id: "rus.1.promotion.relegation",
    sport: "soccer",
    label: "Russian Premier League Relegation/Promotion Playoffs",
    short: "RUSSIAN PR",
    region: "RUS",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rus.1.promotion.relegation", parser: "team" },
  },
  {
    id: "uefa.euro",
    sport: "soccer",
    label: "UEFA European Championship",
    short: "EURO",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.euro", parser: "team" },
  },
  {
    id: "uefa.euro.u19",
    sport: "soccer",
    label: "UEFA European Under-19 Championship",
    short: "EURO UNDER",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.euro.u19", parser: "team" },
  },
  {
    id: "uefa.w.nations",
    sport: "soccer",
    label: "UEFA Women's Nations League",
    short: "WOMEN'S NA",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.w.nations", parser: "team" },
  },
  {
    id: "usa.open",
    sport: "soccer",
    label: "U.S. Open Cup",
    short: "U.S. OPEN ",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.open", parser: "team" },
  },
  {
    id: "usa.usl.l1.cup",
    sport: "soccer",
    label: "USL Cup",
    short: "USL CUP",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.usl.l1.cup", parser: "team" },
  },
  {
    id: "afc.asian.cup",
    sport: "soccer",
    label: "AFC Asian Cup",
    short: "AFC ASIAN ",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.asian.cup", parser: "team" },
  },
  {
    id: "afc.champions",
    sport: "soccer",
    label: "AFC Champions League Elite",
    short: "AFC CHAMPI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.champions", parser: "team" },
  },
  {
    id: "afc.cup",
    sport: "soccer",
    label: "AFC Champions League Two",
    short: "AFC CHAMPI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.cup", parser: "team" },
  },
  {
    id: "afc.cupq",
    sport: "soccer",
    label: "AFC Asian Cup Qualifiers",
    short: "AFC CUP QU",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.cupq", parser: "team" },
  },
  {
    id: "afc.saff.championship",
    sport: "soccer",
    label: "SAFF Championship",
    short: "SAFF CHAMP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.saff.championship", parser: "team" },
  },
  {
    id: "afc.w.asian.cup",
    sport: "soccer",
    label: "AFC Women's Asian Cup",
    short: "AFC WOMEN'",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "afc.w.asian.cup", parser: "team" },
  },
  {
    id: "arg.1",
    sport: "soccer",
    label: "Argentine Liga Profesional de F\u00fatbol",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.1", parser: "team" },
  },
  {
    id: "arg.3",
    sport: "soccer",
    label: "Argentine Primera B",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.3", parser: "team" },
  },
  {
    id: "arg.copa",
    sport: "soccer",
    label: "Copa Argentina",
    short: "COPA ARGEN",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.copa", parser: "team" },
  },
  {
    id: "arg.copa-de-la-superliga",
    sport: "soccer",
    label: "Argentine Copa de la Superliga",
    short: "ASUPERPLIG",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.copa_de_la_superliga", parser: "team" },
  },
  {
    id: "arg.supercopa",
    sport: "soccer",
    label: "Argentine Supercopa",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.supercopa", parser: "team" },
  },
  {
    id: "arg.supercopa.internacional",
    sport: "soccer",
    label: "Argentine Supercopa Internacional",
    short: "SUPERCOPA ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.supercopa.internacional", parser: "team" },
  },
  {
    id: "arg.trofeo-de-la-campeones",
    sport: "soccer",
    label: "Argentine Trofeo de Campeones",
    short: "ARGENTINE ",
    region: "ARG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "arg.trofeo_de_la_campeones", parser: "team" },
  },
  {
    id: "aus.1",
    sport: "soccer",
    label: "Australian A-League Men",
    short: "A-LEAGUE M",
    region: "AUS",
    streamCategory: "football",
    espn: { sport: "soccer", path: "aus.1", parser: "team" },
  },
  {
    id: "aus.w.1",
    sport: "soccer",
    label: "Australian A-League Women",
    short: "A-LEAGUE W",
    region: "AUS",
    streamCategory: "football",
    espn: { sport: "soccer", path: "aus.w.1", parser: "team" },
  },
  {
    id: "aut.1",
    sport: "soccer",
    label: "Austrian Bundesliga",
    short: "AUSTRIAN B",
    region: "AUT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "aut.1", parser: "team" },
  },
  {
    id: "bangabandhu.cup",
    sport: "soccer",
    label: "Bangabandhu Cup",
    short: "BGC",
    region: "BANGAB",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bangabandhu.cup", parser: "team" },
  },
  {
    id: "bel.1",
    sport: "soccer",
    label: "Belgian Pro League",
    short: "BELGIAN PR",
    region: "BEL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bel.1", parser: "team" },
  },
  {
    id: "bel.promotion.relegation",
    sport: "soccer",
    label: "Belgian Pro League Promotion/Relegation Playoffs",
    short: "BELGIAN PR",
    region: "BEL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bel.promotion.relegation", parser: "team" },
  },
  {
    id: "bol.copa",
    sport: "soccer",
    label: "Copa Bolivia",
    short: "COPA BOLIV",
    region: "BOL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bol.copa", parser: "team" },
  },
  {
    id: "bol.ply.rel",
    sport: "soccer",
    label: "Bolivian Liga Profesional Promotion/Relegation Playoffs",
    short: "BOLIVIAN L",
    region: "BOL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bol.ply.rel", parser: "team" },
  },
  {
    id: "bra.camp.gaucho",
    sport: "soccer",
    label: "Brazilian Campeonato Gaucho",
    short: "BRAZIL GAU",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.camp.gaucho", parser: "team" },
  },
  {
    id: "bra.camp.mineiro",
    sport: "soccer",
    label: "Brazilian Campeonato Mineiro",
    short: "BRAZIL MIN",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.camp.mineiro", parser: "team" },
  },
  {
    id: "bra.camp.paulista",
    sport: "soccer",
    label: "Brazilian Campeonato Paulista",
    short: "BRAZIL PAU",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.camp.paulista", parser: "team" },
  },
  {
    id: "bra.copa-do-nordeste",
    sport: "soccer",
    label: "Copa do Nordeste",
    short: "COPA DO NO",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.copa_do_nordeste", parser: "team" },
  },
  {
    id: "bra.supercopa-do-brazil",
    sport: "soccer",
    label: "Brazilian Supercopa Rei",
    short: "SUPERCOPA ",
    region: "BRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "bra.supercopa_do_brazil", parser: "team" },
  },
  {
    id: "caf.champions",
    sport: "soccer",
    label: "CAF Champions League",
    short: "CAF CHAMPI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.champions", parser: "team" },
  },
  {
    id: "caf.championship",
    sport: "soccer",
    label: "African Nations Championship",
    short: "CHAN",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.championship", parser: "team" },
  },
  {
    id: "caf.championship-qual",
    sport: "soccer",
    label: "African Nations Championship Qualifying",
    short: "CHAN QUALI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.championship_qual", parser: "team" },
  },
  {
    id: "caf.confed",
    sport: "soccer",
    label: "CAF Confederation Cup",
    short: "CAF CONFED",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.confed", parser: "team" },
  },
  {
    id: "caf.nations",
    sport: "soccer",
    label: "Africa Cup of Nations",
    short: "AFRICA CUP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "caf.nations", parser: "team" },
  },
  {
    id: "campeones.cup",
    sport: "soccer",
    label: "Campeones Cup",
    short: "CAMPEONES ",
    region: "CAMPEO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "campeones.cup", parser: "team" },
  },
  {
    id: "chi.1",
    sport: "soccer",
    label: "Chilean Primera Divisi\u00f3n",
    short: "CHILEAN PR",
    region: "CHI",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chi.1", parser: "team" },
  },
  {
    id: "chi.1.promotion.relegation",
    sport: "soccer",
    label: "Chilean Primera Divisi\u00f3n Promotion/Relegation Playoffs",
    short: "CHILEAN PR",
    region: "CHI",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chi.1.promotion.relegation", parser: "team" },
  },
  {
    id: "chi.super-cup",
    sport: "soccer",
    label: "Chilean Supercopa",
    short: "CHILEAN SU",
    region: "CHI",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chi.super_cup", parser: "team" },
  },
  {
    id: "chn.1",
    sport: "soccer",
    label: "Chinese Super League",
    short: "CHINESE SU",
    region: "CHN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "chn.1", parser: "team" },
  },
  {
    id: "col.1",
    sport: "soccer",
    label: "Colombian Primera A",
    short: "COLOMBIAN ",
    region: "COL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "col.1", parser: "team" },
  },
  {
    id: "col.2",
    sport: "soccer",
    label: "Colombian Primera B",
    short: "COLOMBIAN ",
    region: "COL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "col.2", parser: "team" },
  },
  {
    id: "col.copa",
    sport: "soccer",
    label: "Copa Colombia",
    short: "COPA COLOM",
    region: "COL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "col.copa", parser: "team" },
  },
  {
    id: "col.superliga",
    sport: "soccer",
    label: "Colombian Superliga",
    short: "COLOMBIAN ",
    region: "COL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "col.superliga", parser: "team" },
  },
  {
    id: "concacaf.champions",
    sport: "soccer",
    label: "Concacaf Champions Cup",
    short: "CONCACAF C",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.champions", parser: "team" },
  },
  {
    id: "concacaf.champions-cup",
    sport: "soccer",
    label: "CONCACAF Champions Cup",
    short: "CONC CC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.champions_cup", parser: "team" },
  },
  {
    id: "concacaf.confederations-playoff",
    sport: "soccer",
    label: "Concacaf Cup",
    short: "CONF PL",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.confederations_playoff", parser: "team" },
  },
  {
    id: "concacaf.u23",
    sport: "soccer",
    label: "CONCACAF U23 Tournament",
    short: "CONC U23",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.u23", parser: "team" },
  },
  {
    id: "concacaf.w.gold",
    sport: "soccer",
    label: "Concacaf W Gold Cup",
    short: "W GOLD CUP",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "concacaf.w.gold", parser: "team" },
  },
  {
    id: "conmebol.america",
    sport: "soccer",
    label: "Copa Am\u00e9rica",
    short: "COPA AM\u00c9RI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "conmebol.america", parser: "team" },
  },
  {
    id: "conmebol.america.femenina",
    sport: "soccer",
    label: "Copa Am\u00e9rica Femenina",
    short: "COPA AM\u00c9RI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "conmebol.america.femenina", parser: "team" },
  },
  {
    id: "conmebol.recopa",
    sport: "soccer",
    label: "CONMEBOL Recopa",
    short: "CONMEBOL R",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "conmebol.recopa", parser: "team" },
  },
  {
    id: "crc.1",
    sport: "soccer",
    label: "Costa Rican Primera Division",
    short: "LIGA FPD",
    region: "CRC",
    streamCategory: "football",
    espn: { sport: "soccer", path: "crc.1", parser: "team" },
  },
  {
    id: "den.1",
    sport: "soccer",
    label: "Danish Superliga",
    short: "DANISH SUP",
    region: "DEN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "den.1", parser: "team" },
  },
  {
    id: "eng.2",
    sport: "soccer",
    label: "English League Championship",
    short: "EFL CHAMPI",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.2", parser: "team" },
  },
  {
    id: "eng.3",
    sport: "soccer",
    label: "English League One",
    short: "EFL LEAGUE",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.3", parser: "team" },
  },
  {
    id: "eng.4",
    sport: "soccer",
    label: "English League Two",
    short: "EFL LEAGUE",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.4", parser: "team" },
  },
  {
    id: "eng.5",
    sport: "soccer",
    label: "English National League",
    short: "NATIONAL L",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.5", parser: "team" },
  },
  {
    id: "eng.charity",
    sport: "soccer",
    label: "English FA Community Shield",
    short: "COMMUNITY ",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.charity", parser: "team" },
  },
  {
    id: "eng.fa",
    sport: "soccer",
    label: "English FA Cup",
    short: "ENGLISH FA",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.fa", parser: "team" },
  },
  {
    id: "eng.league-cup",
    sport: "soccer",
    label: "English Carabao Cup",
    short: "CARABAO CU",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.league_cup", parser: "team" },
  },
  {
    id: "eng.trophy",
    sport: "soccer",
    label: "English EFL Trophy",
    short: "EFL TROPHY",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.trophy", parser: "team" },
  },
  {
    id: "eng.w.fa",
    sport: "soccer",
    label: "English Women's FA Cup",
    short: "WOMEN'S FA",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.w.fa", parser: "team" },
  },
  {
    id: "eng.w.league-cup",
    sport: "soccer",
    label: "English Women's League Cup",
    short: "WOMEN'S LE",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.w.league_cup", parser: "team" },
  },
  {
    id: "eng.w.promotion.relegation",
    sport: "soccer",
    label: "English Women's Super League Promotion/Relegation Playoff",
    short: "WOMEN'S SU",
    region: "ENG",
    streamCategory: "football",
    espn: { sport: "soccer", path: "eng.w.promotion.relegation", parser: "team" },
  },
  {
    id: "esp.2",
    sport: "soccer",
    label: "Spanish LALIGA 2",
    short: "LALIGA 2",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.2", parser: "team" },
  },
  {
    id: "esp.copa-de-la-reina",
    sport: "soccer",
    label: "Spanish Copa de la Reina",
    short: "COPA DE LA",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.copa_de_la_reina", parser: "team" },
  },
  {
    id: "esp.copa-del-rey",
    sport: "soccer",
    label: "Spanish Copa del Rey",
    short: "COPA DEL R",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.copa_del_rey", parser: "team" },
  },
  {
    id: "esp.joan-gamper",
    sport: "soccer",
    label: "Trofeo Joan Gamper",
    short: "TROFEO JOA",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.joan_gamper", parser: "team" },
  },
  {
    id: "esp.super-cup",
    sport: "soccer",
    label: "Spanish Supercopa",
    short: "SPANISH SU",
    region: "ESP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "esp.super_cup", parser: "team" },
  },
  {
    id: "euroamericana.supercopa",
    sport: "soccer",
    label: "SuperCopa Euroamericana",
    short: "SC EA",
    region: "EUROAM",
    streamCategory: "football",
    espn: { sport: "soccer", path: "euroamericana.supercopa", parser: "team" },
  },
  {
    id: "fifa.concacaf.olympicsq",
    sport: "soccer",
    label: "Men's Olympic Qualifying Playoff",
    short: "MEN'S OLYM",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.concacaf.olympicsq", parser: "team" },
  },
  {
    id: "fifa.friendly",
    sport: "soccer",
    label: "International Friendly",
    short: "MEN'S INTE",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.friendly", parser: "team" },
  },
  {
    id: "fifa.intercontinental-cup",
    sport: "soccer",
    label: "FIFA Intercontinental Cup",
    short: "INTERCONTI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.intercontinental_cup", parser: "team" },
  },
  {
    id: "fifa.intercontinental.cup",
    sport: "soccer",
    label: "Intercontinental Cup (India)",
    short: "INTERCONTI",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.intercontinental.cup", parser: "team" },
  },
  {
    id: "fifa.olympics",
    sport: "soccer",
    label: "Men's Olympic Soccer Tournament",
    short: "MEN'S OLYM",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.olympics", parser: "team" },
  },
  {
    id: "fifa.w.concacaf.olympicsq",
    sport: "soccer",
    label: "Concacaf Women's Olympic Qualifying",
    short: "CONCACAF W",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.w.concacaf.olympicsq", parser: "team" },
  },
  {
    id: "fifa.w.olympics",
    sport: "soccer",
    label: "Women's Olympic Soccer Tournament",
    short: "WOMEN'S OL",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.w.olympics", parser: "team" },
  },
  {
    id: "fifa.world.u20",
    sport: "soccer",
    label: "FIFA Under-20 World Cup",
    short: "FIFA U-20 ",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.world.u20", parser: "team" },
  },
  {
    id: "fifa.worldq.afc",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - AFC",
    short: "WCQ - AFC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.afc", parser: "team" },
  },
  {
    id: "fifa.worldq.afc.conmebol",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - AFC/CONMEBOL Playoff",
    short: "WCQ - AFC/",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.afc.conmebol", parser: "team" },
  },
  {
    id: "fifa.worldq.caf",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - CAF",
    short: "WCQ - CAF",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.caf", parser: "team" },
  },
  {
    id: "fifa.worldq.concacaf.ofc",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - Concacaf/OFC Playoff",
    short: "WCQ - CONC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.concacaf.ofc", parser: "team" },
  },
  {
    id: "fifa.worldq.ofc",
    sport: "soccer",
    label: "FIFA World Cup Qualifying - OFC",
    short: "WCQ - OFC",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.worldq.ofc", parser: "team" },
  },
  {
    id: "fifa.wwc",
    sport: "soccer",
    label: "FIFA Women's World Cup",
    short: "FIFA WOMEN",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fifa.wwc", parser: "team" },
  },
  {
    id: "fra.1.promotion.relegation",
    sport: "soccer",
    label: "French Ligue 1 Promotion/Relegation Playoffs",
    short: "LIGUE 1 PR",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.1.promotion.relegation", parser: "team" },
  },
  {
    id: "fra.coupe-de-france",
    sport: "soccer",
    label: "Coupe de France",
    short: "COUPE DE F",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.coupe_de_france", parser: "team" },
  },
  {
    id: "fra.super-cup",
    sport: "soccer",
    label: "French Trophee des Champions",
    short: "TROPHEE DE",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.super_cup", parser: "team" },
  },
  {
    id: "fra.w.1",
    sport: "soccer",
    label: "French Premi\u00e8re Ligue",
    short: "PREMI\u00c8RE L",
    region: "FRA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "fra.w.1", parser: "team" },
  },
  {
    id: "friendly.emirates-cup",
    sport: "soccer",
    label: "Emirates Cup",
    short: "EMIRATES C",
    region: "FRIEND",
    streamCategory: "football",
    espn: { sport: "soccer", path: "friendly.emirates_cup", parser: "team" },
  },
  {
    id: "ger.2.promotion.relegation",
    sport: "soccer",
    label: "German Bundesliga 2. Promotion/Relegation Playoffs",
    short: "2. BUNDESL",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.2.promotion.relegation", parser: "team" },
  },
  {
    id: "ger.dfb-pokal",
    sport: "soccer",
    label: "German Cup",
    short: "GERMAN CUP",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.dfb_pokal", parser: "team" },
  },
  {
    id: "ger.playoff.relegation",
    sport: "soccer",
    label: "German Bundesliga Promotion/Relegation Playoff",
    short: "BUNDESLIGA",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.playoff.relegation", parser: "team" },
  },
  {
    id: "ger.super-cup",
    sport: "soccer",
    label: "German Supercup",
    short: "GERMAN SUP",
    region: "GER",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ger.super_cup", parser: "team" },
  },
  {
    id: "global.champs-cup",
    sport: "soccer",
    label: "International Champions Cup",
    short: "CHAMPIONS ",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.champs_cup", parser: "team" },
  },
  {
    id: "global.club-challenge",
    sport: "soccer",
    label: "CONMEBOL-UEFA Club Challenge",
    short: "CONMEBOL-U",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.club_challenge", parser: "team" },
  },
  {
    id: "global.finalissima",
    sport: "soccer",
    label: "CONMEBOL-UEFA Cup of Champions",
    short: "MEN'S FINA",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.finalissima", parser: "team" },
  },
  {
    id: "global.gulf-cup",
    sport: "soccer",
    label: "Arabian Gulf Cup",
    short: "ARABIAN GU",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.gulf_cup", parser: "team" },
  },
  {
    id: "global.u20.intercontinental-cup",
    sport: "soccer",
    label: "CONMEBOL-UEFA U20 Intercontinental Cup",
    short: "U20 INTERC",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.u20.intercontinental_cup", parser: "team" },
  },
  {
    id: "global.w.finalissima",
    sport: "soccer",
    label: "CONMEBOL-UEFA Women's Cup of Champions",
    short: "WOMEN'S FI",
    region: "GLOBAL",
    streamCategory: "football",
    espn: { sport: "soccer", path: "global.w.finalissima", parser: "team" },
  },
  {
    id: "gua.1",
    sport: "soccer",
    label: "Guatemalan Liga Nacional",
    short: "GUATEMALAN",
    region: "GUA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "gua.1", parser: "team" },
  },
  {
    id: "hon.1",
    sport: "soccer",
    label: "Honduran Liga Nacional",
    short: "HONDURAN L",
    region: "HON",
    streamCategory: "football",
    espn: { sport: "soccer", path: "hon.1", parser: "team" },
  },
  {
    id: "ind.2",
    sport: "soccer",
    label: "Indian I-League",
    short: "INDIAN I-L",
    region: "IND",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ind.2", parser: "team" },
  },
  {
    id: "ir1.1.promotion.relegation",
    sport: "soccer",
    label: "Irish Premier Division Promotion/Relegation Playoffs",
    short: "IRISH PREM",
    region: "IR1",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ir1.1.promotion.relegation", parser: "team" },
  },
  {
    id: "ita.2",
    sport: "soccer",
    label: "Italian Serie B",
    short: "ITALIAN SE",
    region: "ITA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ita.2", parser: "team" },
  },
  {
    id: "ita.coppa-italia",
    sport: "soccer",
    label: "Coppa Italia",
    short: "COPPA ITAL",
    region: "ITA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ita.coppa_italia", parser: "team" },
  },
  {
    id: "ita.super-cup",
    sport: "soccer",
    label: "Italian Supercoppa",
    short: "ITALIAN SU",
    region: "ITA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ita.super_cup", parser: "team" },
  },
  {
    id: "jpn.world-challenge",
    sport: "soccer",
    label: "Japanese J.League World Challenge",
    short: "J.LEAGUE W",
    region: "JPN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "jpn.world_challenge", parser: "team" },
  },
  {
    id: "mex.2",
    sport: "soccer",
    label: "Mexican Liga de Expansi\u00f3n MX",
    short: "LIGA DE EX",
    region: "MEX",
    streamCategory: "football",
    espn: { sport: "soccer", path: "mex.2", parser: "team" },
  },
  {
    id: "mex.campeon",
    sport: "soccer",
    label: "Mexican Campeon de Campeones",
    short: "CAMPEON DE",
    region: "MEX",
    streamCategory: "football",
    espn: { sport: "soccer", path: "mex.campeon", parser: "team" },
  },
  {
    id: "ned.1",
    sport: "soccer",
    label: "Dutch Eredivisie",
    short: "EREDIVISIE",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.1", parser: "team" },
  },
  {
    id: "ned.3.promotion.relegation",
    sport: "soccer",
    label: "Dutch Tweede Divisie Promotion/Relegation Playoffs",
    short: "DUTCH PLAY",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.3.promotion.relegation", parser: "team" },
  },
  {
    id: "ned.cup",
    sport: "soccer",
    label: "Dutch KNVB Beker",
    short: "KNVB BEKER",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.cup", parser: "team" },
  },
  {
    id: "ned.playoff.relegation",
    sport: "soccer",
    label: "Dutch Eredivisie Promotion/Relegation Playoffs",
    short: "EREDIVISIE",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.playoff.relegation", parser: "team" },
  },
  {
    id: "ned.supercup",
    sport: "soccer",
    label: "Dutch Johan Cruyff Shield",
    short: "JOHAN CRUY",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.supercup", parser: "team" },
  },
  {
    id: "ned.w.eredivisie-cup",
    sport: "soccer",
    label: "Dutch Eredivisie Cup",
    short: "DUTCH ERED",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.w.eredivisie_cup", parser: "team" },
  },
  {
    id: "ned.w.knvb-cup",
    sport: "soccer",
    label: "Dutch KNVB Beker Vrouwen",
    short: "DUTCH VROU",
    region: "NED",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ned.w.knvb_cup", parser: "team" },
  },
  {
    id: "nonfifa",
    sport: "soccer",
    label: "Non-FIFA Friendly",
    short: "NON-FIFA F",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "nonfifa", parser: "team" },
  },
  {
    id: "nor.1",
    sport: "soccer",
    label: "Norwegian Eliteserien",
    short: "NORWEGIAN ",
    region: "NOR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "nor.1", parser: "team" },
  },
  {
    id: "nor.1.promotion.relegation",
    sport: "soccer",
    label: "Norwegian Eliteserien Promotion/Relegation Playoffs",
    short: "NORWEGIAN ",
    region: "NOR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "nor.1.promotion.relegation", parser: "team" },
  },
  {
    id: "par.1.supercopa",
    sport: "soccer",
    label: "Paraguayan Supercopa",
    short: "PARAGUAYAN",
    region: "PAR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "par.1.supercopa", parser: "team" },
  },
  {
    id: "por.1.promotion.relegation",
    sport: "soccer",
    label: "Portuguese Primeira Liga Promotion/Relegation Playoffs",
    short: "PORTUGUESE",
    region: "POR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "por.1.promotion.relegation", parser: "team" },
  },
  {
    id: "por.taca.portugal",
    sport: "soccer",
    label: "Taca de Portugal",
    short: "TACA DE PO",
    region: "POR",
    streamCategory: "football",
    espn: { sport: "soccer", path: "por.taca.portugal", parser: "team" },
  },
  {
    id: "rsa.1.promotion.relegation",
    sport: "soccer",
    label: "South African Premiership Promotion/Relegation Playoffs",
    short: "SOUTH AFRI",
    region: "RSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rsa.1.promotion.relegation", parser: "team" },
  },
  {
    id: "rsa.mtn8",
    sport: "soccer",
    label: "South African MTN 8 Cup",
    short: "SOUTH AFRI",
    region: "RSA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "rsa.mtn8", parser: "team" },
  },
  {
    id: "sco.1",
    sport: "soccer",
    label: "Scottish Premiership",
    short: "SPFL PREMI",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.1", parser: "team" },
  },
  {
    id: "sco.1.promotion.relegation",
    sport: "soccer",
    label: "Scottish Premiership Promotion/Relegation Playoffs",
    short: "SPFL PREMI",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.1.promotion.relegation", parser: "team" },
  },
  {
    id: "sco.2.promotion.relegation",
    sport: "soccer",
    label: "Scottish Championship Promotion/Relegation Playoffs",
    short: "SPFL CHAMP",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.2.promotion.relegation", parser: "team" },
  },
  {
    id: "sco.challenge",
    sport: "soccer",
    label: "Scottish League Challenge Cup",
    short: "SPFL CHALL",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.challenge", parser: "team" },
  },
  {
    id: "sco.tennents",
    sport: "soccer",
    label: "Scottish Cup",
    short: "SCOTTISH C",
    region: "SCO",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sco.tennents", parser: "team" },
  },
  {
    id: "sgp.1",
    sport: "soccer",
    label: "Singaporean Premier League",
    short: "SINGAPORE ",
    region: "SGP",
    streamCategory: "football",
    espn: { sport: "soccer", path: "sgp.1", parser: "team" },
  },
  {
    id: "slv.1",
    sport: "soccer",
    label: "Salvadoran Primera Division",
    short: "SALVADORAN",
    region: "SLV",
    streamCategory: "football",
    espn: { sport: "soccer", path: "slv.1", parser: "team" },
  },
  {
    id: "swe.1",
    sport: "soccer",
    label: "Swedish Allsvenskan",
    short: "SWEDISH AL",
    region: "SWE",
    streamCategory: "football",
    espn: { sport: "soccer", path: "swe.1", parser: "team" },
  },
  {
    id: "swe.1.promotion.relegation",
    sport: "soccer",
    label: "Swedish Allsvenskan Promotion/Relegation Playoffs",
    short: "SWEDISH AL",
    region: "SWE",
    streamCategory: "football",
    espn: { sport: "soccer", path: "swe.1.promotion.relegation", parser: "team" },
  },
  {
    id: "uefa.euro-u21",
    sport: "soccer",
    label: "UEFA European Under-21 Championship",
    short: "EURO UNDER",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.euro_u21", parser: "team" },
  },
  {
    id: "uefa.europa.conf",
    sport: "soccer",
    label: "UEFA Conference League",
    short: "UEFA CONFE",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.europa.conf", parser: "team" },
  },
  {
    id: "uefa.super-cup",
    sport: "soccer",
    label: "UEFA Super Cup",
    short: "UEFA SUPER",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.super_cup", parser: "team" },
  },
  {
    id: "uefa.w.europa",
    sport: "soccer",
    label: "UEFA Women's Europa Cup",
    short: "WOMEN'S EU",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.w.europa", parser: "team" },
  },
  {
    id: "uefa.wchampions",
    sport: "soccer",
    label: "UEFA Women's Champions League",
    short: "UEFA WOMEN",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.wchampions", parser: "team" },
  },
  {
    id: "uefa.weuro",
    sport: "soccer",
    label: "UEFA Women's European Championship",
    short: "WOMEN'S EU",
    region: "INT",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uefa.weuro", parser: "team" },
  },
  {
    id: "uru.1",
    sport: "soccer",
    label: "Liga AUF Uruguaya",
    short: "LIGA AUF U",
    region: "URU",
    streamCategory: "football",
    espn: { sport: "soccer", path: "uru.1", parser: "team" },
  },
  {
    id: "usa.ncaa.m.1",
    sport: "soccer",
    label: "NCAA Men's Soccer",
    short: "CMSOC",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.ncaa.m.1", parser: "team" },
  },
  {
    id: "usa.ncaa.w.1",
    sport: "soccer",
    label: "NCAA Women's Soccer",
    short: "CWSOC",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.ncaa.w.1", parser: "team" },
  },
  {
    id: "usa.nwsl.cup",
    sport: "soccer",
    label: "NWSL Challenge Cup",
    short: "NWSL CHALL",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.nwsl.cup", parser: "team" },
  },
  {
    id: "usa.nwsl.summer.cup",
    sport: "soccer",
    label: "NWSL X Liga MX Femenil Summer Cup",
    short: "NWSL/LIGA ",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.nwsl.summer.cup", parser: "team" },
  },
  {
    id: "usa.usl.l1",
    sport: "soccer",
    label: "USL League One",
    short: "USL LEAGUE",
    region: "USA",
    streamCategory: "football",
    espn: { sport: "soccer", path: "usa.usl.l1", parser: "team" },
  },
  {
    id: "ven.1",
    sport: "soccer",
    label: "Venezuelan Primera Divisi\u00f3n",
    short: "LIGA FUTVE",
    region: "VEN",
    streamCategory: "football",
    espn: { sport: "soccer", path: "ven.1", parser: "team" },
  },
] as const satisfies readonly LeagueRegistryEntry[];
