import type { League, Stream } from "../types";
import { parseGameId } from "../game-id";
import type { MediaHostRule, Provider, StreamLookup } from "./types";

export interface FastChannel {
  readonly slug: string;
  readonly name: string;
  readonly league: League;
  readonly url: string;
  readonly quality: Stream["quality"];
  readonly language?: string;
  readonly aliases?: readonly string[];
}

export const FAST_CHANNELS = [
  {
    slug: "accdn",
    name: "ACCDN",
    league: "sports-channels",
    url: "https://raycom-accdn-firetv.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["ACC Digital Network"],
  },
  {
    slug: "pac-12-insider",
    name: "Pac-12 Insider",
    league: "sports-channels",
    url: "https://pac12-firetv.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "stadium",
    name: "Stadium",
    league: "sports-channels",
    url: "https://wurl120sports.global.transmit.live/hls/679a907dce42a042c23ace37/v1/stadium_gracenote/samsung_us/latest/main/hls/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fubo-sports-network",
    name: "fubo Sports Network",
    league: "sports-channels",
    url: "https://dnf08l6u6uxnz.cloudfront.net/master.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["fubo Sports"],
  },
  {
    slug: "lacrosse-tv",
    name: "Lacrosse TV",
    league: "sports-channels",
    url: "https://1840769862.rsc.cdn77.org/FTF/LSN_SCTE.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "billiard-tv",
    name: "Billiard TV",
    league: "sports-channels",
    url: "https://1621590671.rsc.cdn77.org/HLS/BILLIARDTV.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "ftf-sports",
    name: "FTF Sports",
    league: "sports-channels",
    url: "https://1657061170.rsc.cdn77.org/HLS/FTF-LINEAR.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "unbeaten-sports-channel",
    name: "Unbeaten Sports Channel",
    league: "sports-channels",
    url: "https://d1t5afz6qed3xk.cloudfront.net/Unbeaten.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Unbeaten"],
  },
  {
    slug: "draftkings-network",
    name: "DraftKings Network",
    league: "sports-channels",
    url: "https://na.linear.zype.com/e0bd0e23-a958-4e43-8164-4f2fef8876a8/fd3614bd-90bf-4530-a277-65ae3a1720c8-zype/live.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["DK Network"],
  },
  {
    slug: "espn8-the-ocho",
    name: "ESPN8 The Ocho",
    league: "sports-channels",
    url: "https://d3b6q2ou5kp8ke.cloudfront.net/ESPNTheOcho.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["The Ocho"],
  },
  {
    slug: "womens-sports-network",
    name: "Women's Sports Network",
    league: "sports-channels",
    url: "https://d39accvx65hq9o.cloudfront.net/Womens_Sports_Network.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["WSN"],
  },
  {
    slug: "alkass-one",
    name: "Alkass One",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/alkass1-p/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "arryadia",
    name: "Arryadia",
    league: "sports-channels",
    url: "https://stream-lb.livemediama.com/arryadia/hls/master.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "sportitalia-plus",
    name: "Sportitalia Plus",
    league: "sports-channels",
    url: "https://sportsitalia-samsungitaly.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "tvs-bowling",
    name: "TVS Bowling Network",
    league: "sports-channels",
    url: "https://rpn.bozztv.com/gusa/gusa-tvsbowling/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "tvs-women-sports",
    name: "TVS Women Sports",
    league: "sports-channels",
    url: "https://rpn.bozztv.com/gusa/gusa-tvswsn/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "africa-24-sport",
    name: "Africa 24 Sport",
    league: "sports-channels",
    url: "https://africa24.vedge.infomaniak.com/livecast/ik:africa24sport/manifest.m3u8",
    quality: "HD",
    language: "FR",
  },
  {
    slug: "al-iraqia-sport",
    name: "Al Iraqia Sport",
    league: "sports-channels",
    url: "https://imn-live.esite-lab.com/hls/iraqia-sports-1.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "bek-tv-sports-west",
    name: "BEK TV Sports West",
    league: "sports-channels",
    url: "https://cdn3.wowza.com/5/ZWQ1K2NYTmpFbGsr/BEK-WOWZA-1/smil:BEKPRIMEW.smil/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["BEK Sports West"],
  },
  {
    slug: "dd-sports",
    name: "DD Sports",
    league: "sports-channels",
    url: "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
    quality: "HD",
    language: "HI",
  },
  {
    slug: "more-than-sports-tv",
    name: "More Than Sports TV",
    league: "sports-channels",
    url: "https://mts1.iptv-playoutcenter.de/mts/mts-web/playlist.m3u8",
    quality: "HD",
    language: "DE",
    aliases: ["MTS TV"],
  },
  {
    slug: "red-bull-tv",
    name: "Red Bull TV",
    league: "sports-channels",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sportitalia",
    name: "Sportitalia",
    league: "sports-channels",
    url: "https://edge-001.streamup.eu/sportitalia/sihd_abr/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "talksport",
    name: "talkSPORT",
    league: "sports-channels",
    url: "https://af7a8b4e.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctZ2JfdGFsa1NQT1JUX0hMUw/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "trace-sport-stars",
    name: "Trace Sport Stars",
    league: "sports-channels",
    url: "https://lightning-tracesport-samsungau.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Trace Sport Stars AU"],
  },
  {
    slug: "ksa-sports-1",
    name: "KSA Sports 1",
    league: "sports-channels",
    url: "https://aloula-redirect.vercel.app/9/playlist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "ksa-sports-2",
    name: "KSA Sports 2",
    league: "sports-channels",
    url: "https://aloula-redirect.vercel.app/10/playlist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "ksa-sports-3",
    name: "KSA Sports 3",
    league: "sports-channels",
    url: "https://aloula-redirect.vercel.app/16/playlist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "ktv-sport",
    name: "KTV Sport",
    league: "sports-channels",
    url: "https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "ktv-sport-plus",
    name: "KTV Sport Plus",
    league: "sports-channels",
    url: "https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "oman-sports-tv",
    name: "Oman Sports TV",
    league: "sports-channels",
    url: "https://partneta.cdn.mgmlcdn.com/omsport/smil:omsport.stream.smil/chunklist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "mnb-sport",
    name: "MNB Sport",
    league: "sports-channels",
    url: "https://live.mnb.mn/hls/mnb_sport.stream.m3u8",
    quality: "HD",
    language: "MN",
  },
  {
    slug: "bahrain-sports-1",
    name: "Bahrain Sports 1",
    league: "sports-channels",
    url: "https://5c7b683162943.streamlock.net/live/ngrp:sportsone_all/playlist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "bahrain-sports-2",
    name: "Bahrain Sports 2",
    league: "sports-channels",
    url: "https://5c7b683162943.streamlock.net/live/ngrp:bahrainsportstwo_all/playlist.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "jordan-sport",
    name: "Jordan Sport",
    league: "sports-channels",
    url: "http://93.184.10.248/JordanSport/index.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "realitatea-sportiva",
    name: "Realitatea Sportiva",
    league: "sports-channels",
    url: "https://stream.realitatea.net/realitatea/sportiva_md/ts:playlist.m3u8",
    quality: "HD",
    language: "RO",
  },
  {
    slug: "alkass-two",
    name: "Alkass Two",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/alkass2-p/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "alkass-three",
    name: "Alkass Three",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/alkass3-p/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "alkass-four",
    name: "Alkass Four",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/alkass4-p/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "alkass-six",
    name: "Alkass Six",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/alkass6-p/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "alkass-shoof",
    name: "Alkass Shoof",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/shooflive/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "alkass-shoof-2",
    name: "Alkass Shoof 2",
    league: "sports-channels",
    url: "https://liveeu-gcp.alkassdigital.net/shooflive2/main.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "arryadia-hd-1",
    name: "Arryadia HD 1",
    league: "sports-channels",
    url: "https://stream-lb.livemediama.com/arryadia-hd-01/hls/master.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "arryadia-hd-2",
    name: "Arryadia HD 2",
    league: "sports-channels",
    url: "https://stream-lb.livemediama.com/arryadia-hd-02/hls/master.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "arryadia-hd-3",
    name: "Arryadia HD 3",
    league: "sports-channels",
    url: "https://stream-lb.livemediama.com/arryadia-hd-03/hls/master.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "arryadia-hd-tnt",
    name: "Arryadia HD TNT",
    league: "sports-channels",
    url: "https://stream-lb.livemediama.com/arryadia-tnt/hls/master.m3u8",
    quality: "HD",
    language: "AR",
  },
  {
    slug: "a-spor",
    name: "A Spor",
    league: "sports-channels",
    url: "https://rnttwmjcin.turknet.ercdn.net/lcpmvefbyo/aspor/aspor.m3u8",
    quality: "HD",
    language: "TR",
  },
  {
    slug: "ado-tv",
    name: "ADO TV",
    league: "sports-channels",
    url: "https://strhls.streamakaci.tv/ortb/ortb2-multi/playlist.m3u8",
    quality: "HD",
    language: "FR",
  },
  {
    slug: "atg-live",
    name: "ATG Live",
    league: "sports-channels",
    url: "https://kanal75xto-llhls.akamaized.net/live/Data/atg-kanal-15-02a-rr/HLS-Legacy-HL/atg-kanal-15-02a-rr.m3u8",
    quality: "HD",
    language: "SV",
  },
  {
    slug: "cazetv",
    name: "CazeTV",
    league: "sports-channels",
    url: "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/Caze_TV.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "colimdot-tv",
    name: "ColimdoT TV",
    league: "sports-channels",
    url: "https://cnn.livestreaminggroup.info:3132/live/colimdotvlive.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "ct-sport",
    name: "CT Sport",
    league: "sports-channels",
    url: "http://88.212.15.19/live/test_ctsport_25p/playlist.m3u8",
    quality: "HD",
    language: "CS",
  },
  {
    slug: "flohockey-247",
    name: "FloHockey 24/7",
    league: "sports-channels",
    url: "https://amg02278-amg02278c2-flosports-worldwide-9916.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FloHockey"],
  },
  {
    slug: "fuel-tv",
    name: "Fuel TV",
    league: "sports-channels",
    url: "https://amg01074-fueltv-amg01074c1-stirr-us-4214.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "game-plus",
    name: "Game+",
    league: "sports-channels",
    url: "https://a-cdn.klowdtv.com/live2/fntsy_720p/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "horse-tv",
    name: "Horse TV",
    league: "sports-channels",
    url: "https://a-cdn.klowdtv.com/live2/horsetv_720p/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "mlb-channel",
    name: "MLB Channel",
    league: "sports-channels",
    url: "https://pb-2y9ox4r1fy550.akamaized.net/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "nautical-channel",
    name: "Nautical Channel",
    league: "sports-channels",
    url: "https://a-cdn.klowdtv.com/live2/nautical_720p/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "nfl-channel",
    name: "NFL Channel",
    league: "sports-channels",
    url: "https://pb-we3ltka9xobj6.akamaized.net/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "strongman-champions-league",
    name: "Strongman Champions League",
    league: "sports-channels",
    url: "https://rightsboosterltd-scl-2-eu.rakuten.wurl.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Strongman"],
  },
  {
    slug: "tr-sport",
    name: "TR Sport",
    league: "sports-channels",
    url: "https://livetr.teleromagna.it/mia/live/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "tsn-the-ocho",
    name: "TSN The Ocho",
    league: "sports-channels",
    url: "https://d3pnbvng3bx2nj.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-rds8g35qfqrnv/TSN_The_Ocho.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "turkmenistan-sport",
    name: "Turkmenistan Sport",
    league: "sports-channels",
    url: "https://alpha.tv.online.tm/hls/ch004.m3u8",
    quality: "HD",
    language: "TK",
  },
  {
    slug: "tvr-sport",
    name: "TVR Sport",
    league: "sports-channels",
    url: "https://tvr-sport.lg.mncdn.com/tvrsport/smil:tvrsport.smil/chunklist_b5160000.m3u8",
    quality: "HD",
    language: "RO",
  },
  {
    slug: "tvs-classic-sports",
    name: "TVS Classic Sports",
    league: "sports-channels",
    url: "https://rpn.bozztv.com/gusa/gusa-tvs/index.m3u8",
    quality: "SD",
    language: "EN",
  },
  {
    slug: "tvs-sports",
    name: "TVS Sports",
    league: "sports-channels",
    url: "https://rpn.bozztv.com/gusa/gusa-tvssports/index.m3u8",
    quality: "SD",
    language: "EN",
  },
  {
    slug: "tvs-sports-bureau",
    name: "TVS Sports Bureau",
    league: "sports-channels",
    url: "https://rpn.bozztv.com/gusa/gusa-tvssportsbureau/index.m3u8",
    quality: "SD",
    language: "EN",
  },
  {
    slug: "world-of-freesports",
    name: "World of Freesports",
    league: "sports-channels",
    url: "https://mainstreammedia-worldoffreesportsintl-rakuten.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "cbs-sports-hq",
    name: "CBS Sports HQ",
    league: "sports-channels",
    url: "https://propee33f9c2.airspace-cdn.cbsivideo.com/index.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["CBS Sports"],
  },
  {
    slug: "sportsgrid",
    name: "SportsGrid",
    league: "sports-channels",
    url: "https://sportsgrid-tribal.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Sports Grid"],
  },
  {
    slug: "nhl-channel",
    name: "NHL Channel",
    league: "sports-channels",
    url: "https://nhl-firetv.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["NHL"],
  },
  {
    slug: "antenasport",
    name: "AntenaSport",
    league: "sports-channels",
    url: "https://stream1.antenaplay.ro/as/asrolive1/playlist.m3u8",
    quality: "HD",
    language: "RO",
  },
  {
    slug: "tour-spot-tv",
    name: "Tour Spot TV",
    league: "sports-channels",
    url: "https://fox.hostlagarto.com:8081/toursporttv/playlist.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["Tour Sport TV"],
  },
  {
    slug: "tv-cuatro-43",
    name: "TV Cuatro 4.3",
    league: "sports-channels",
    url: "https://5ca3e84a76d30.streamlock.net/tv43gto/tv43gto.smil/.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["TVCuatro Deportes"],
  },
  {
    slug: "ovacion-tv",
    name: "Ovacion TV",
    league: "sports-channels",
    url: "http://cdn2.ujjina.com:1935/iptvovacion1/liveovacion1tv/playlist.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "rete-8-sport",
    name: "Rete 8 Sport",
    league: "sports-channels",
    url: "https://64b16f23efbee.streamlock.net/rete8sport/rete8sport/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "sport2u",
    name: "Sport2U",
    league: "sports-channels",
    url: "https://stream9.xdevel.com/video0s976916-1685/stream/playlist_dvr.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "sportoutdoor-tv",
    name: "SportOutdoor.tv",
    league: "sports-channels",
    url: "https://gto2000-sportoutdoortv-1-it.samsung.wurl.tv/playlist.m3u8",
    quality: "HD",
    language: "IT",
    aliases: ["Sport Outdoor TV"],
  },
  {
    slug: "horse-country-tv",
    name: "Horse & Country TV",
    league: "sports-channels",
    url: "https://hnc-free-viewlift.amagi.tv/HNC_AUSTRALIA.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Horse and Country"],
  },
  {
    slug: "belarus-5",
    name: "Belarus 5",
    league: "sports-channels",
    url: "https://ngtrk.dc.beltelecom.by/ngtrk/smil:belarus5.smil/playlist.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "varzesh-tv",
    name: "Varzesh TV",
    league: "sports-channels",
    url: "https://ncdn.telewebion.ir/varzesh/live/playlist.m3u8",
    quality: "HD",
    language: "FA",
  },
  {
    slug: "kozoom-tv",
    name: "Kozoom TV",
    league: "sports-channels",
    url: "https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/fdd6f243-f971-4a1a-9510-97ac01d6b37f/manifest.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Kozoom"],
  },
  {
    slug: "slvr",
    name: "SLVR",
    league: "sports-channels",
    url: "https://dnwqx9ivbd7ay.cloudfront.net/bbb/samshow/samshow.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "victory-plus",
    name: "Victory+",
    league: "sports-channels",
    url: "https://d2otd2h2i5t24h.cloudfront.net/Victory_National.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Victory Plus"],
  },
  {
    slug: "roku-sports-channel",
    name: "Roku Sports Channel",
    league: "sports-channels",
    url: "https://d3ialx0k0mla2a.cloudfront.net/Roku_Sports_Channel.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Roku Sports"],
  },
  {
    slug: "fox-sports-fast",
    name: "FOX Sports FAST",
    league: "sports-channels",
    url: "https://d1jzu95oc8fgt3.cloudfront.net/FOX_Sports.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FOX Sports"],
  },
  {
    slug: "hnc-sports",
    name: "HNC Sports",
    league: "sports-channels",
    url: "https://hncfree-samsung-uk.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "huntstream",
    name: "HuntStream",
    league: "sports-channels",
    url: "https://huntstream-viewlift.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "msg-sportszone",
    name: "MSG SportsZone",
    league: "sports-channels",
    url: "https://d2a31kzot4f8t3.cloudfront.net/v1/amc_msgsportszone_1/samsungheadend_us/latest/main/hls/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "surf-cinema",
    name: "Surf Cinema",
    league: "sports-channels",
    url: "https://amg13231-actve-amg13231c4-samsung-au-2990.playouts.now.amagi.tv/playlist/amg13231-actvefast-surfer-samsungau/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "outdoor-channel",
    name: "Outdoor Channel",
    league: "sports-channels",
    url: "https://amg00718-outdoorchannela-outdoortv-samsungau-uc7mp.amagi.tv/playlist/amg00718-outdoorchannela-outdoortv-samsungau/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "htspor-tv",
    name: "HT Spor TV",
    league: "sports-channels",
    url: "https://ciner.daioncdn.net/ht-spor/ht-spor.m3u8?app=web",
    quality: "HD",
    language: "TR",
  },
  {
    slug: "ge-fast",
    name: "GE FAST",
    league: "sports-channels",
    url: "https://amg00716-globo-amg00716c1-tcl-br-9495.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "tele-rebelde",
    name: "Tele Rebelde",
    league: "sports-channels",
    url: "https://tv.picta.cu/telerebelde/telerebelde_1.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "madeinbo-tv",
    name: "MadeinBO TV",
    league: "sports-channels",
    url: "https://srvx1.selftv.video/dmchannel/live/playlist.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "premier-sports",
    name: "Premier Sports",
    league: "sports-channels",
    url: "https://amg19223-amg19223c3-amgplt0351.playout.now3.amagi.tv/playlist/amg19223-amg19223c3-amgplt0351/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "premier-sports-2",
    name: "Premier Sports 2",
    league: "sports-channels",
    url: "https://amg19223-amg19223c4-amgplt0351.playout.now3.amagi.tv/playlist/amg19223-amg19223c4-amgplt0351/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "world-poker-tour",
    name: "World Poker Tour",
    league: "sports-channels",
    url: "https://amg00477-samsungelectron-worldpokertour-samsunguk-81igb.amagi.tv/playlist/amg00477-samsungelectron-worldpokertour-samsunguk/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["WPT"],
  },
  {
    slug: "blast-sports-2",
    name: "Blast Sports 2",
    league: "sports-channels",
    url: "https://amg19223-amg19223c2-amgplt0351.playout.now3.amagi.tv/playlist/amg19223-amg19223c2-amgplt0351/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "waypoint-tv",
    name: "Waypoint TV",
    league: "sports-channels",
    url: "https://amg00381-amg00381c1-freelivesports-emea-11030.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg00381-waypointcommunicationsfast-waypoint-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "equalympic",
    name: "Equalympic",
    league: "sports-channels",
    url: "https://iptv.prosto.tv/ch215/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fast-and-funbox",
    name: "Fast&FunBox",
    league: "sports-channels",
    url: "https://iptv.prosto.tv/ch120/index.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Fast and FunBox"],
  },
  {
    slug: "introuble",
    name: "INTROUBLE",
    league: "sports-channels",
    url: "https://amg00861-amg00861c6-stirr-us-8229.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sports-connect",
    name: "Sports Connect",
    league: "sports-channels",
    url: "https://streamdot.broadpeak.io/cff02a74da64d1459391ce1f72d58f1a/afxpstr/SportsConnect/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "all-sports-television-network",
    name: "All Sports Television Network",
    league: "sports-channels",
    url: "https://2-fss-2.streamhoster.com/pl_118/204972-2205186-1/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["W14DK-D 14.5"],
  },
  {
    slug: "midpen-youth-education-sports",
    name: "Midpen Youth Education and Sports",
    league: "sports-channels",
    url: "https://5c2974786200d.streamlock.net/live-chan28/ngrp:ch28_all/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Midpen Channel 28"],
  },
  {
    slug: "ekol-sports",
    name: "Ekol Sports",
    league: "sports-channels",
    url: "https://ekoltv-live.ercdn.net/ekolsport/ekolsport.m3u8",
    quality: "HD",
    language: "TR",
  },
  {
    slug: "pokergo",
    name: "PokerGO",
    league: "sports-channels",
    url: "https://linear-426.frequency.stream/dist/localnow/426/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Poker Go"],
  },
  {
    slug: "rodeo-tv",
    name: "Rodeo TV",
    league: "sports-channels",
    url: "https://amg17292-amg17292c1-distrotv-us-4170.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "surfer",
    name: "SURFER",
    league: "sports-channels",
    url: "https://amg13231-actve-amg13231c4-plex-us-1821.playouts.now.amagi.tv/playlist/amg13231-actvefast-surfer-plexus/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "aym-sports",
    name: "AYM Sports",
    league: "sports-channels",
    url: "https://aym-as.otteravision.com/aym/as/as.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "gopro",
    name: "GoPro",
    league: "sports-channels",
    url: "https://linear-891.frequency.stream/mt/freelivesports/891/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "wired2fish",
    name: "Wired2Fish",
    league: "sports-channels",
    url: "https://linear-80.frequency.stream/mt/sportstribaltv/80/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "itv-deportes",
    name: "ITV Deportes",
    league: "sports-channels",
    url: "https://thm-it-roku.otteravision.com/thm/it/it.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "viju-sport",
    name: "viju+ Sport",
    league: "sports-channels",
    url: "https://stream8.cinerama.uz/1229/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "astrakhan-ru-sport",
    name: "Astrakhan.Ru Sport",
    league: "sports-channels",
    url: "https://streaming.astrakhan.ru/astrakhanrusporthd/playlist.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "cowboy-plus-sports",
    name: "Cowboy+ Sports",
    league: "sports-channels",
    url: "https://amg17292-amg17292c1-freelivesports-emea-6961.playouts.now.amagi.tv/playlist/amg17292-tetonridgellc-tetonridgefast-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Cowboy Channel"],
  },
  {
    slug: "eurovision-sport",
    name: "Eurovision Sport",
    league: "sports-channels",
    url: "https://amg01763-amg01763c2-amgplt0201.playout.now3.amagi.tv/ts-eu-w1-n2/playlist/amg01763-amg01763c2-amgplt0201/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "extreme-channel",
    name: "Extreme Channel",
    league: "sports-channels",
    url: "https://amg26268-amg26268c16-freelivesports-emea-10881.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg26268-sportsstudio-ssextreme-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Extreme"],
  },
  {
    slug: "free-live-sports",
    name: "Free Live Sports",
    league: "sports-channels",
    url: "https://amg26268-amg26268c27-amgplt0201.playout.now3.amagi.tv/ts-eu-w1-n2/playlist/amg26268-amg26268c27-amgplt0201/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FLS"],
  },
  {
    slug: "game-and-fish-tv",
    name: "Game & Fish TV",
    league: "sports-channels",
    url: "https://amg00436-amg00436c7-freelivesports-emea-8457.playouts.now.amagi.tv/playlist/amg00436-ksemotvholdingsfast-gameandfishtv-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Game Fish TV"],
  },
  {
    slug: "horizon-sports",
    name: "Horizon Sports",
    league: "sports-channels",
    url: "https://horizonsports.b-cdn.net/horizonsports-global/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "rvtv",
    name: "RVTV",
    league: "sports-channels",
    url: "https://amg26268-amg26268c13-freelivesports-emea-10224.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg26268-sportsstudio-rvtv-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "tyc-sports",
    name: "TyC Sports",
    league: "sports-channels",
    url: "https://amg26268-amg26268c14-freelivesports-emea-10267.playouts.now.amagi.tv/ts-us-e2-n2/playlist/amg26268-sportsstudio-tycsports-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "ftv-bolivia",
    name: "FTV Bolivia",
    league: "sports-channels",
    url: "https://master.tucableip.com/ftvhd/index.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["FTV"],
  },
  {
    slug: "hard-knocks",
    name: "Hard Knocks",
    league: "sports-channels",
    url: "https://d3uyzhwvmemdyf.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/HardKnocks-PLEX/121.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "htv-sports",
    name: "HTV Sports",
    league: "sports-channels",
    url: "https://live.fptplay53.net/epzhd1/htvcthethao_vhls.smil/chunklist.m3u8",
    quality: "HD",
    language: "VI",
  },
  {
    slug: "irib-3",
    name: "IRIB 3",
    league: "sports-channels",
    url: "https://ncdn.telewebion.ir/tv3/live/playlist.m3u8",
    quality: "HD",
    language: "FA",
    aliases: ["TV3 Iran"],
  },
  {
    slug: "nbc-sports-now",
    name: "NBC Sports NOW",
    league: "sports-channels",
    url: "https://xumo-xumoent-vc-122-sjv70.fast.nbcuni.com/live/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "qazsport",
    name: "QazSport",
    league: "sports-channels",
    url: "https://qazsporttv-stream.qazcdn.com/qazsporttv/qazsporttv/playlist.m3u8",
    quality: "SD",
    language: "KK",
  },
  {
    slug: "strongman",
    name: "Strongman",
    league: "sports-channels",
    url: "https://rightsboosterltd-scl-1-gb.samsung.wurl.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "vtv6",
    name: "VTV6",
    league: "sports-channels",
    url: "https://vtvgolive-failover.vtvdigital.vn/vtvgo/vtv6tt-manifest.m3u8",
    quality: "HD",
    language: "VI",
  },
  {
    slug: "khl",
    name: "KHL",
    league: "sports-channels",
    url: "https://stream8.cinerama.uz/1028/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "sport-uz",
    name: "Sport UZ",
    league: "sports-channels",
    url: "https://stream8.cinerama.uz/1004/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "UZ",
  },
  {
    slug: "as3-sport-tv",
    name: "AS3 Sport TV",
    league: "sports-channels",
    url: "https://streamtv.as3sport.online:3394/hybrid/play.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "astrakhan-ru-sport",
    name: "Astrakhan.Ru Sport",
    league: "sports-channels",
    url: "https://streaming.astrakhan.ru/astrakhanrusporthd/tracks-v3a1/index.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "outdoor-america",
    name: "Outdoor America",
    league: "sports-channels",
    url: "https://d1e354daam8g5r.cloudfront.net/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "surfing-plus",
    name: "Surfing+",
    league: "sports-channels",
    url: "https://dr4jwhk0sty71.cloudfront.net/scheduler/scheduleMaster/444.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "world-surf-league-24-7",
    name: "World Surf League 24/7",
    league: "sports-channels",
    url: "https://eed754f7.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X1dvcmxkU3VyZkxlYWd1ZTI0N19ITFM/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sports-illustrated-tv",
    name: "Sports Illustrated TV",
    league: "sports-channels",
    url: "https://c5879d53.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X1NJVFZfSExT/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "world-of-free-sport",
    name: "World of Free Sport",
    league: "sports-channels",
    url: "https://amg01866-mmagfast-amg01866c4-hp-us-10725.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "unique-sports",
    name: "Unique Sports",
    league: "sports-channels",
    url: "https://pop.uniquetv.com.br/uniquesports1/video.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "rs-sports",
    name: "RS Sports",
    league: "sports-channels",
    url: "https://cdn-tiva-video07-logicahost-com-br.smartbit.co/rssports01/rssports01/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "rs-sports-2",
    name: "RS Sports 2",
    league: "sports-channels",
    url: "https://cdn-tiva-video07-logicahost-com-br.smartbit.co/rssports02/rssports02/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "rs-sports-3",
    name: "RS Sports 3",
    league: "sports-channels",
    url: "https://cdn-tiva-video07-logicahost-com-br.smartbit.co/rssports03/rssports03/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "duck-hunting-tv",
    name: "Duck Hunting TV",
    league: "sports-channels",
    url: "https://main.duckhunting.playout.vju.tv/duckhuntingtv/main.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "italian-fishing-tv",
    name: "Italian Fishing TV",
    league: "sports-channels",
    url: "https://fms.premio.link/fishingtv/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "outdoor-action-tv",
    name: "Outdoor Action TV",
    league: "sports-channels",
    url: "https://careco-outdoor-action-1-us.tcl.wurl.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "glory-kickboxing-brazil",
    name: "GLORY Kickboxing Brazil",
    league: "combat-events",
    url: "https://87e5452b.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/VENMLWJyX0dsb3J5S2lja2JveGluZ19ITFM/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "hbcu-go",
    name: "HBCU Go",
    league: "sports-channels",
    url: "https://amg00876-allenmedia-hbcugo-localnow-v0547.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "play-tv-horse",
    name: "Play TV Horse",
    league: "sports-channels",
    url: "https://cdn-tiva-video04-logicahost-com-br.smartbit.co/playtvhorse/playtvhorse/playlist.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "tv-da-pesca",
    name: "TV da Pesca",
    league: "sports-channels",
    url: "https://isaocorp.cloudecast.com/tvdapesca/index.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "nsports-fast",
    name: "Nsports FAST",
    league: "sports-channels",
    url: "https://cc-zv5hyc9jj47n5.akamaized.net/ogc/nsprt/nsprt.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "canal-goat",
    name: "Canal Goat",
    league: "world-football",
    url: "https://cng-cngt-samsungtvplus-br.otteravision.com/cng/cngt/cngt.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "racer-brasil",
    name: "Racer Brasil",
    league: "motorsports",
    url: "https://dfr80qz435crc.cloudfront.net/EFGH/Amagi/7N_Sports/MAVTV_Brasil_BR/MAVTV_Brasil.m3u8",
    quality: "HD",
    language: "PT",
  },
  {
    slug: "xtreme-outdoor",
    name: "Xtreme Outdoor",
    league: "sports-channels",
    url: "https://fb6ae464.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctY2FfWHRyZW1lT3V0ZG9vcklOVExfSExT/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "horse-and-country",
    name: "Horse and Country",
    league: "sports-channels",
    url: "https://amg00810-hctvltd-hncfree-localnow-t4eey.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "flosports-racing",
    name: "FloSports Racing",
    league: "motorsports",
    url: "https://amg02278-flosports-amg02278c1-hp-us-11065.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "pga-tour",
    name: "PGA Tour",
    league: "pga",
    url: "https://d11k1mnrgfposz.cloudfront.net/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "30a-golf-kingdom",
    name: "30A Golf Kingdom",
    league: "pga",
    url: "https://30a-tv.com/feeds/vidaa/golf.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "golfpass",
    name: "GolfPass",
    league: "pga",
    url: "https://d2icntm6fhxrry.cloudfront.net/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "golf-network",
    name: "Golf Network",
    league: "pga",
    url: "https://amg26268-amg26268c12-freelivesports-emea-9477.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg26268-sportsstudio-golfnetworkchannel-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "cbs-sports-golazo",
    name: "CBS Sports Golazo Network",
    league: "world-football",
    url: "https://proped3fhg87.airspace-cdn.cbsivideo.com/golazo-live-dai/master/golazo-live-dai.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Golazo"],
  },
  {
    slug: "bein-xtra-es",
    name: "beIN Sports XTRA en Espanol",
    league: "world-football",
    url: "https://dc1644a9jazgj.cloudfront.net/beIN_Sports_Xtra_Espanol.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["beIN XTRA Espanol"],
  },
  {
    slug: "fifa-plus-us",
    name: "FIFA+ United States",
    league: "world-football",
    url: "https://d2w9q46ikgrcwx.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-of5cbk3sav3w5/v1/sysdata_s_p_a_fifa_7/samsungheadend_us/latest/main/hls/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FIFA+"],
  },
  {
    slug: "fifa-plus-spain",
    name: "FIFA+ Spain",
    league: "world-football",
    url: "https://d63fabad.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWVzX0ZJRkFQbHVzU3BhbmlzaF9ITFM/playlist.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["FIFA+ Spanish"],
  },
  {
    slug: "fifa-plus-women",
    name: "FIFA+ Women",
    league: "world-football",
    url: "https://cffda8ff.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U2Ftc3VuZy1nYl9GSUZBUGx1c3dvbWVuX0hMUw/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "bein-sports-xtra",
    name: "beIN SPORTS XTRA",
    league: "world-football",
    url: "https://bein-xtra-bein.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["beIN XTRA"],
  },
  {
    slug: "gol-classics",
    name: "Gol Classics",
    league: "world-football",
    url: "https://d71gqtnep83vb.cloudfront.net/gol_classics/gol_classics.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "fifa-plus-french",
    name: "FIFA+ French",
    league: "world-football",
    url: "https://37b4c228.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWZyX0ZJRkFQbHVzRnJlbmNoX0hMUw/playlist.m3u8",
    quality: "HD",
    language: "FR",
    aliases: ["FIFA+ France"],
  },
  {
    slug: "fifa-plus-german",
    name: "FIFA+ German",
    league: "world-football",
    url: "https://4397879b.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWRlX0ZJRkFQbHVzR2VybWFuX0hMUw/playlist.m3u8",
    quality: "HD",
    language: "DE",
    aliases: ["FIFA+ Germany"],
  },
  {
    slug: "fifa-plus-italian",
    name: "FIFA+ Italian",
    league: "world-football",
    url: "https://5d95f7d7.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWl0X0ZJRkFQbHVzSXRhbGlhbl9ITFM/playlist.m3u8",
    quality: "HD",
    language: "IT",
    aliases: ["FIFA+ Italy"],
  },
  {
    slug: "fifa-plus-hispanic-america",
    name: "FIFA+ Hispanic America",
    league: "world-football",
    url: "https://6c849fb3.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctbXhfRklGQVBsdXNTcGFuaXNoLTFfSExT/playlist.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["FIFA+ Espanol"],
  },
  {
    slug: "fifa-plus-portuguese",
    name: "FIFA+ Portuguese",
    league: "world-football",
    url: "https://e3be9ac5.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctYnJfRklGQVBsdXNQb3J0dWd1ZXNlX0hMUw/playlist.m3u8",
    quality: "HD",
    language: "PT",
    aliases: ["FIFA+ Brasil"],
  },
  {
    slug: "real-madrid-tv",
    name: "Real Madrid TV",
    league: "world-football",
    url: "https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/master.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["Real Madrid TV Espanol"],
  },
  {
    slug: "real-madrid-tv-english",
    name: "Real Madrid TV English",
    league: "world-football",
    url: "https://rmtv.akamaized.net/hls/live/2043154/rmtv-en-web/master.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Real Madrid TV EN"],
  },
  {
    slug: "fb-tv",
    name: "FB TV",
    league: "world-football",
    url: "http://1hskrdto.rocketcdn.com/fenerbahcetv.smil/playlist.m3u8",
    quality: "HD",
    language: "TR",
    aliases: ["Fenerbahce TV"],
  },
  {
    slug: "inter-tv",
    name: "Inter TV",
    league: "world-football",
    url: "https://ilglobotv-live.akamaized.net/channels/InterTV/Live.m3u8",
    quality: "HD",
    language: "IT",
    aliases: ["Inter Milan TV"],
  },
  {
    slug: "gfn-football",
    name: "GFN Football",
    league: "world-football",
    url: "https://e562e489.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U2Ftc3VuZy1nYl9HRk5Tb2NjZXJfSExT/manifest.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["GFN Soccer"],
  },
  {
    slug: "futbol-tv",
    name: "Futbol TV",
    league: "world-football",
    url: "https://live.teleradiocom.tj/8/3m.m3u8",
    quality: "HD",
    language: "TG",
  },
  {
    slug: "top-barca-espanol",
    name: "Top Barca en Espanol",
    league: "world-football",
    url: "https://amg17560-amg17560c2-freelivesports-emea-10992.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg17560-fcbarcelona-topbarcaspanish-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["Top Barca Spanish"],
  },
  {
    slug: "top-barca",
    name: "Top Barca",
    league: "world-football",
    url: "https://amg17560-amg17560c1-freelivesports-emea-10991.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg17560-fcbarcelona-topbarcaenglish-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Top Barca English"],
  },
  {
    slug: "foosball-tv",
    name: "Foosball TV",
    league: "world-football",
    url: "https://amg00585-sportstribal-amg00585c2-sportstribal-emea-2176.playouts.now.amagi.tv/playlist/amg00585-sportstribaltvfast-foosballtv-sportstribalemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sportitalia-solocalcio",
    name: "Sportitalia Solocalcio",
    league: "world-football",
    url: "https://edge-001.streamup.eu/sportitalia/sisolocalcio_abr/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "cricket-gold",
    name: "Cricket Gold",
    league: "cricket",
    url: "https://d1nj4u39ja4cn0.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/FLS-MuxIP-CricketGold/418.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "willow-sports",
    name: "Willow Sports",
    league: "cricket",
    url: "https://amg01269-amg01269c1-sportstribal-emea-5204.playouts.now.amagi.tv/playlist/amg01269-willowtvfast-willowplus-sportstribalemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Willow TV"],
  },
  {
    slug: "perfect-game-tv",
    name: "Perfect Game TV",
    league: "mlb",
    url: "https://6ebc93db.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/U3BvcnRzVHJpYmFsLWV1X1BlcmZlY3RHYW1lVFZfSExT/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Perfect Game"],
  },
  {
    slug: "bleav-football",
    name: "Bleav Football",
    league: "gridiron",
    url: "https://linear-493.frequency.stream/dist/glewedtv/493/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "nhra-tv",
    name: "NHRA TV",
    league: "motorsports",
    url: "https://d265y4sk8257lt.cloudfront.net/nh.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "f1-channel",
    name: "F1 Channel",
    league: "motorsports",
    url: "https://amg12058-c15studio-amg12058c1-lg-us-5787.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "aci-sport-tv",
    name: "ACI Sport TV",
    league: "motorsports",
    url: "https://webstream.multistream.it/memfs/e2cb3629-c1a2-495b-b43a-9eb386f04ed8.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "fanduel-racing",
    name: "FanDuel Racing",
    league: "motorsports",
    url: "https://d3ehq1uaxory6w.cloudfront.net/out/v1/35c05f080f4e49a4b4eb031b5a14e505/TVG2index_2.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fanduel-tv",
    name: "FanDuel TV",
    league: "motorsports",
    url: "https://d2jl8r92tdc3f1.cloudfront.net/out/v1/59419700344b4625b7cb0693ba265ea3/TVGindex_1.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "floracing-247",
    name: "FloRacing 24/7",
    league: "motorsports",
    url: "https://amg02278-amg02278c1-flosports-worldwide-7592.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FloRacing"],
  },
  {
    slug: "racer-select",
    name: "Racer Select",
    league: "motorsports",
    url: "https://amg00378-amg00378c4-freelivesports-emea-5637.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "racer-international",
    name: "RACER International",
    league: "motorsports",
    url: "https://amg00378-mavtv-amg00378c3-sportstribal-emea-1325.playouts.now.amagi.tv/playlist/amg00378-mavtvfast-motorsportsnetworkint-sportstribalemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Racer Network"],
  },
  {
    slug: "30a-we-love-cars",
    name: "30A We Love Cars",
    league: "motorsports",
    url: "https://30a-tv.com/feeds/vidaa/cars.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "curiosity-motores",
    name: "Curiosity Motores",
    league: "motorsports",
    url: "https://d5ts03kapml2e.cloudfront.net/CuriosityMotores.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "auto-plus",
    name: "Auto Plus",
    league: "motorsports",
    url: "https://stream8.cinerama.uz/1036/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "drive-ru",
    name: "Drive",
    league: "motorsports",
    url: "https://stream8.cinerama.uz/1421/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "RU",
  },
  {
    slug: "choppertown",
    name: "Choppertown",
    league: "motorsports",
    url: "https://linear-11.frequency.stream/dist/glewedtv/11/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "motorracing",
    name: "MotorRacing",
    league: "motorsports",
    url: "https://horizonsports.b-cdn.net/motorracing-global/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Motor Racing"],
  },
  {
    slug: "nascar",
    name: "NASCAR",
    league: "motorsports",
    url: "https://amg00115-amg00115c1-freelivesports-emea-11215.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg00115-nascar-nascar-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["NASCAR Racing"],
  },
  {
    slug: "monster-jam",
    name: "Monster Jam",
    league: "motorsports",
    url: "https://4b9627c7.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X01vbnN0ZXJKYW1fSExT/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sky-racing-1",
    name: "Sky Racing 1",
    league: "motorsports",
    url: "https://636ffd31f0e12.streamlock.net/RacingStream1/RacingStream1/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "sky-racing-2",
    name: "Sky Racing 2",
    league: "motorsports",
    url: "https://636ffd31f0e12.streamlock.net/RacingStream2/RacingStream2/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "teletrak",
    name: "Teletrak",
    league: "motorsports",
    url: "https://unlimited6-cl.dps.live/sportinghd/sportinghd.smil/playlist.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "tjk-tv",
    name: "TJK TV",
    league: "motorsports",
    url: "https://tjktv-live.tjk.org/tjktv.m3u8",
    quality: "HD",
    language: "TR",
  },
  {
    slug: "tvs-turbo",
    name: "TVS Turbo",
    league: "motorsports",
    url: "https://rpn.bozztv.com/gusa/gusa-tvsturbo/index.m3u8",
    quality: "SD",
    language: "EN",
  },
  {
    slug: "motortrend-fast-tv",
    name: "MotorTrend FAST TV",
    league: "motorsports",
    url: "https://live-manifest.production-public.tubi.io/live/e7be5ad5-9044-4151-95d4-a9aae10ab0a5/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["MotorTrend"],
  },
  {
    slug: "rally-tv",
    name: "Rally TV",
    league: "motorsports",
    url: "https://rally-tv-live.akamaized.net/hls/live/2117704/RallyTV-Pri/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "canal-motor",
    name: "Canal Motor",
    league: "motorsports",
    url: "https://digicom.hls.iptvdc.com/canalmotor/index.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "garage-tv-latin-america",
    name: "Garage TV Latin America",
    league: "motorsports",
    url: "https://stream1.sersat.com/hls/garagetv.m3u8",
    quality: "HD",
    language: "ES",
    aliases: ["Garage TV"],
  },
  {
    slug: "motori-tv",
    name: "Motori TV",
    league: "motorsports",
    url: "https://5f22d76e220e1.streamlock.net/servizio01/servizio01/playlist.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "powernation",
    name: "PowerNation",
    league: "motorsports",
    url: "https://amg01258-raycomsports-powernationau-samsungau-18bwc.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "turf-movil",
    name: "Turf Movil",
    league: "motorsports",
    url: "https://tvturf4.janus.cl/playlist/stream.m3u8?d=w&id=",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "kcmn-mtrspt1",
    name: "KCMN-LD6 MTRSPT1",
    league: "motorsports",
    url: "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02873-kravemedia-mtrspt1-distrotv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["MTRSPT1"],
  },
  {
    slug: "cars-stars-tv",
    name: "Cars & Stars TV",
    league: "motorsports",
    url: "https://iptv.prosto.tv/ch111/index.m3u8",
    quality: "HD",
    language: "RU",
    aliases: ["Cars and Stars TV"],
  },
  {
    slug: "tna-wrestling-channel",
    name: "TNA Wrestling Channel",
    league: "wrestling",
    url: "https://amg00966-amg00966c1-freelivesports-emea-7712.playouts.now.amagi.tv/playlist/amg00966-anthem-tnawrestling-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fite-247",
    name: "FITE 24/7",
    league: "combat-events",
    url: "https://d3d85c7qkywguj.cloudfront.net/scheduler/scheduleMaster/263.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["FITE"],
  },
  {
    slug: "swerve-combat",
    name: "Swerve Combat",
    league: "combat-events",
    url: "https://linear-253.frequency.stream/mt/roku/253/hls/master/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "unbeaten-north-america",
    name: "Unbeaten North America",
    league: "combat-events",
    url: "https://amg00721-amg00721c5-freelivesports-emea-9593.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg00721-inverleigh-unbeaten-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Unbeaten"],
  },
  {
    slug: "pfl-mma",
    name: "PFL MMA",
    league: "combat-events",
    url: "https://a883593c.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X1BGTE1NQV9ITFM/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Professional Fighters League"],
  },
  {
    slug: "tvs-boxing",
    name: "TVS Boxing",
    league: "combat-events",
    url: "https://rpn.bozztv.com/gusa/gusa-tvsboxing/index.m3u8",
    quality: "SD",
    language: "EN",
  },
  {
    slug: "glory-kickboxing",
    name: "GLORY Kickboxing",
    league: "combat-events",
    url: "https://6f972d29.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X0dsb3J5S2lja2JveGluZ19ITFM/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["GLORY"],
  },
  {
    slug: "persiana-fight",
    name: "Persiana Fight",
    league: "combat-events",
    url: "https://fighthls.persiana.live/hls/stream.m3u8",
    quality: "HD",
    language: "FA",
  },
  {
    slug: "mma-tv",
    name: "MMA-TV",
    league: "combat-events",
    url: "http://31.148.48.15/M1_Global/index.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["M1 Global"],
  },
  {
    slug: "arena-fight",
    name: "Arena Fight",
    league: "combat-events",
    url: "https://nl1.nghk.ai/ArenaFight/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fight-network-fast",
    name: "Fight Network",
    league: "combat-events",
    url: "https://amg00966-amg00966c10-amgplt0201.playout.now3.amagi.tv/playlist/amg00966-amg00966c10-amgplt0201/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fightbox",
    name: "FightBox",
    league: "combat-events",
    url: "https://iptv.prosto.tv/ch118/index.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "fight-tv",
    name: "Fight TV",
    league: "combat-events",
    url: "https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/70e45fc8-1f6c-4492-ac26-9868f70f4e02/manifest.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "mma-tv-com",
    name: "MMA-TV.com",
    league: "combat-events",
    url: "https://stream8.cinerama.uz/1226/tracks-v1a1/mono.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["MMA TV"],
  },
  {
    slug: "combatv",
    name: "CombaTV",
    league: "combat-events",
    url: "https://aym-cbtv.otteravision.com/aym/cbtv/cbtv_1080p.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "lucha-plus",
    name: "Lucha Plus",
    league: "combat-events",
    url: "https://amg17334-amg17334c1-freelivesports-emea-7386.playouts.now.amagi.tv/playlist/amg17334-luchalibrefast-luchalibre-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "ES",
  },
  {
    slug: "dazn-combat",
    name: "DAZN Combat",
    league: "combat-events",
    url: "https://dazn-combat-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-dazn-combat-rakuten/CDN/master.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "golden-boy-boxing",
    name: "Golden Boy Boxing",
    league: "combat-events",
    url: "https://goldenboy.duckhunting.playout.vju.tv/DuckhuntingTV_GoldenBoy/main.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["Golden Boy"],
  },
  {
    slug: "overtime",
    name: "Overtime",
    league: "basketball-events",
    url: "https://d1a8aq6t30gkqj.cloudfront.net/v1/amc_overtime_1/samsungheadend_us/latest/main/hls/playlist_hd.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "nba-tv-fast",
    name: "NBA TV",
    league: "basketball-events",
    url: "https://amg00556-amg00556c3-firetv-us-6060.playouts.now.amagi.tv/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["NBA TV FAST"],
  },
  {
    slug: "tennis-channel",
    name: "Tennis Channel",
    league: "tennis-events",
    url: "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01444-tennischannelth-tennischannelnl-samsungnl/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "tennis-channel-international",
    name: "Tennis Channel International",
    league: "tennis-events",
    url: "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg01444-tennischannelth-tennischnlintl-sportstribal/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["The Tennis Channel"],
  },
  {
    slug: "tennis-channel-t2",
    name: "Tennis Channel T2",
    league: "tennis-events",
    url: "https://amg01444-amg01444c2-freelivesports-emea-11541.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg01444-tennischannelfast-tennischannelus-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
    aliases: ["T2"],
  },
  {
    slug: "pickleball-tv",
    name: "Pickleball TV",
    league: "tennis-events",
    url: "https://amg01444-amg01444c3-freelivesports-emea-11542.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg01444-tennischannelfast-pickleball-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "supertennis",
    name: "SuperTennis",
    league: "tennis-events",
    url: "https://live-embed.supertennix.hiway.media/restreamer/supertennix_client/gpu-a-c0-16/restreamer/outgest/aa3673f1-e178-44a9-a947-ef41db73211a/manifest.m3u8",
    quality: "HD",
    language: "IT",
  },
  {
    slug: "t2-tv",
    name: "T2 TV",
    league: "tennis-events",
    url: "https://t2hls.wns.live/hls/stream.m3u8",
    quality: "HD",
    language: "EN",
  },
  {
    slug: "tennis-tv-classics",
    name: "Tennis TV Classics",
    league: "tennis-events",
    url: "https://amg01470-amg01470c1-freelivesports-emea-9021.playouts.now.amagi.tv/playlist/amg01470-atpmediaoperationsltdfast-tennistvclassics-freelivesportsemea/playlist.m3u8",
    quality: "HD",
    language: "EN",
  },
] as const satisfies readonly FastChannel[];

function normalize(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function channelNames(channel: FastChannel): string[] {
  return [channel.name, ...(channel.aliases ?? [])].map(normalize);
}

function fastSlugFromGameId(id: string): string | null {
  const parsed = parseGameId(id);
  if (!parsed?.espnId.startsWith("fast:")) return null;
  return parsed.espnId.slice("fast:".length);
}

export function fastChannelsForGame(game: StreamLookup): FastChannel[] {
  const slug = fastSlugFromGameId(game.id);
  if (slug) {
    return FAST_CHANNELS.filter((channel) => channel.slug === slug && channel.league === game.league);
  }

  const names = [
    game.eventName,
    game.shortName,
    game.homeTeam.name,
    game.awayTeam.name,
  ].filter((value): value is string => Boolean(value)).map(normalize);

  return FAST_CHANNELS.filter((channel) => (
    channel.league === game.league
    && channelNames(channel).some((name) => names.includes(name))
  ));
}

function mediaHostRules(): MediaHostRule[] {
  const rules = new Map<string, MediaHostRule>();

  for (const channel of FAST_CHANNELS) {
    const hostname = new URL(channel.url).hostname;
    if (hostname.endsWith(".amagi.tv")) continue;
    if (hostname.endsWith(".linear.zype.com")) continue;
    rules.set(hostname, { hostname });
  }

  rules.set("*.amagi.tv", { hostname: "amagi.tv", includeSubdomains: true });
  rules.set("*.csm.tubi.video", { hostname: "csm.tubi.video", includeSubdomains: true });
  rules.set("*.vedge.infomaniak.com", { hostname: "vedge.infomaniak.com", includeSubdomains: true });
  rules.set("*.linear.zype.com", { hostname: "linear.zype.com", includeSubdomains: true });
  rules.set("*.livestreaminggroup.info", { hostname: "livestreaminggroup.info", includeSubdomains: true });
  rules.set("*.dps.live", { hostname: "dps.live", includeSubdomains: true });
  rules.set("*.sofast.tv", { hostname: "sofast.tv", includeSubdomains: true });
  rules.set("*.frequency.stream", { hostname: "frequency.stream", includeSubdomains: true });
  rules.set("*.b-cdn.net", { hostname: "b-cdn.net", includeSubdomains: true });
  rules.set("*.blivenyc.com", { hostname: "blivenyc.com", includeSubdomains: true });
  rules.set("*.daioncdn.net", { hostname: "daioncdn.net", includeSubdomains: true });
  rules.set("*.prosto.tv", { hostname: "prosto.tv", includeSubdomains: true });
  rules.set("*.telewebion.ir", { hostname: "telewebion.ir", includeSubdomains: true });
  rules.set("*.hostlagarto.com", { hostname: "hostlagarto.com", includeSubdomains: true });
  rules.set("*.dc.beltelecom.by", { hostname: "dc.beltelecom.by", includeSubdomains: true });
  rules.set("*.qazcdn.com", { hostname: "qazcdn.com", includeSubdomains: true });
  rules.set("sofastplaylist.akamaized.net", { hostname: "sofastplaylist.akamaized.net" });
  rules.set("cdn11.crtvnoc.com", { hostname: "cdn11.crtvnoc.com" });
  rules.set("fkwi.com", { hostname: "fkwi.com" });
  rules.set("livecdn.premiumfree.tv", { hostname: "livecdn.premiumfree.tv" });
  rules.set("pub-4f5d7301cc724935bc5fb954cafe28f2.r2.dev", {
    hostname: "pub-4f5d7301cc724935bc5fb954cafe28f2.r2.dev",
  });
  rules.set("live.kwikmotion.com", { hostname: "live.kwikmotion.com" });
  return [...rules.values()];
}

export const fast: Provider = {
  name: "fast",
  capabilities: {
    embedHosts: [],
    mediaHosts: mediaHostRules(),
  },

  async getStreams(game) {
    return fastChannelsForGame(game).map((channel) => ({
      label: channel.name,
      url: channel.url,
      quality: channel.quality,
      language: channel.language,
    }));
  },

  async getCounts(games) {
    return new Map(games.map((game) => [game.id, fastChannelsForGame(game).length]));
  },
};
